Ensembl/ensembl-variation

scripts/export/dump_vep.pl

I forgot to add this last time... Would like to get it into 'origin' so I don't forget next time (and it should be harmless).
Cheers,
Dan.

Adding wheat to the list with SIFT

---

modules/Bio/EnsEMBL/Variation/DBSQL/StudyAdaptor.pm
modules/t/studyAdaptor.t

Current StudyAdaptor lacks a store() method for newly created objects. This functionality is desirable for Ensemblgenomes.

added store() method for StudyAdaptor.pm

---

scripts/misc/healthcheck_vep_caches.pl

VEP caches for non-Ensembl sources (i.e. Ensembl Genomes and VectorBase) will be labelled with versions other than the Ensembl version. The latter is still required for things like setting up registries, so the obvious solution is to introduce a new parameter; it's got the same name as the analagous parameter in the VEP script, --cache_version. If not set, it defaults to --version, so this change should have no impact for Ensembl checks.
While adding this functionality, I found what I think is a bug, where variation features were sought even if there is no variation db. So I wrapped that code in a conditional in another commit.

Enable VEP cache checking script to be used by Ensembl Genomes

---

modules/Bio/EnsEMBL/Variation/Pipeline/DumpVEP/BaseVEP.pm
modules/Bio/EnsEMBL/Variation/Pipeline/DumpVEP/DumpVEP.pm
scripts/misc/healthcheck_vep_caches.pl

Some small changes:
- appending "--pass " to the password only in DumpVEP.pm but not in BaseVEP.pm. This is because the VEP dumping script requires "--pass " but the healthcheck script does not.
- setting the env parameter HC_VEP_CACHE_VERSION to the EG version if we're working with a EG database. Otherwise, this defaults to the Ensembl schema version the healthchecks fail.
- if no password is given (as for an ensro user), it defaults to undef.

Getting the healthchecks to work for an EG database and an ensrw user

---

modules/Bio/EnsEMBL/Variation/Utils/VEP.pm

The warn() function call does not output anything. It just supresses errors, in case there are errors in plugins. warning_msg() is the right function to call.

Report plugins errors.

---

modules/Bio/EnsEMBL/Variation/Source.pm

There are still some instances where we are seeing Bio::EnsEMBL::Variation::Source=HASH(...) strings in some pages or export output. It's not only the web code, but ensembl core API code as well.
This fix is to prevent that from happening and return the actual name of the Source if the Source object is treated as a string.

Deal with unwanted stringified perl object

---

modules/Bio/EnsEMBL/Variation/LDFeatureContainer.pm

Use of keys $hash_ref has been introduced in perl 5.14 and has always been experimental. In 5.24 this syntax throws an error because the support of automatic dereferencing is now removed.
In order to be compatible with perl 5.24 at least one line needs to be modified.

fix for obsolete perl syntax (perl 5.24)

---

modules/Bio/EnsEMBL/Variation/DBSQL/SampleAdaptor.pm
modules/Bio/EnsEMBL/Variation/VCFCollection.pm

Reworked version of this fix for ENSVAR-591.
Those 2 commits change 2 things:
1) The way the sample_adaptor get the list of samples from the db: with one request for both samples and sample_synonyms, when before the synonyms were added after the main samples, in a slow loop. This speeds up things significantly when a lot of sample synonyms are used.
2) The sample data can now correctly be retrieved from a vcf. A small bug in the code was hiding the fact that the initial sample_synonym name was forgotten, which resulted in the samples never being mapped (so only new samples unrelated to the db were retrieved).

Fix vcf sample synonym

---

C_code/ld_vcf.c

Hello @at7, 
here is the bug fix you requested, an '=' character was missing. 
Thanks for the good test case, it helped tremendously,
Daniel

Bug when assessing whether variant of interest was found in LD code

---

modules/Bio/EnsEMBL/Variation/VCFCollection.pm

Two parts bug: instead of looping on all sample_synonyms, only the first
synonym was retrieved at first. So the array ref was dereferenced in a
previous commit, but the second part of the bug was not fixed, which
lead to a string being used as an array.

Fix loop on sample synonyms in get_all_Samples

---

modules/Bio/EnsEMBL/Variation/Utils/BaseVepTabixPlugin.pm

Hi Will,
The linked commit plugs a memory leak in the BaseVepTabixPlugin module that showed with the CADD VEP plugin. For a genome-wide VCF (around 16M variants), VEP previously required in excess of 105 GiB, which is a bit much. With this fix applied, it only requires around 750 MiB throughout.
Thanks,
Michael

Plugged a memory leak in the results cache of BaseVepTabixPlugin

---

modules/Bio/EnsEMBL/Variation/BaseVariationFeature.pm
modules/t/variationFeature.t

Required to fix VEP issue where seq_region_start gets looked up from
DB if VF is on a circular slice.
transfer and transform methods are overridden to prevent issues
with caching.

Add overridden caching versions of seq_region_start, seq_region_end

---

modules/Bio/EnsEMBL/Variation/Utils/Sequence.pm
modules/t/hgvs_parser.t

Update to HGVS writer for substitutions with redundant bases. Input ACT/AGT currently flagged as an inversion, but should be a C>G substitution.

convert single base inversion to a substitution

---

modules/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm
modules/Bio/EnsEMBL/Variation/Pipeline/SetVariationClass.pm
scripts/import/dbSNP/GenericContig.pm
sql/table.sql

Modifications for differences in MySQL versions
- handling of GROUP BY different between 5.6 and 5.7. 
Addresses issues in JIRA ENSVAR-881
- storage_engine deprecated 5.7.5

MySQL version review

---

modules/t/LDFeatureContainerAdaptor.t

The tests don't fail when I run them on the farm. I added the change which seems to let the tests pass. Not entirely sure what is going on. Travis is probably throwing a warning message which is causing problems.

Disable addition of a had_no_warnings test via done_testing

---

modules/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm
modules/t/variationFeatureAdaptor.t

Exception is thrown where HGVS notation spanning more than 5kb is requested

Added region length check

---

modules/Bio/EnsEMBL/Variation/Utils/VEP.pm
modules/t/phenotypeFeatureAdaptor.t
modules/t/vep.t

The tests for 5.26 failed because of an unknown _escape_ method in VEP.pm. I fixed it but if you have better suggestions for dealing with this let me know.

Fix use escape

---

.travis.yml

I tried different ways to tell travis to install version 2.9. Let me know if you have a better suggestion. 
There is a newer version of Bio::DB::HTS v2.10 which causes problems with ensembl-io/release/92.
(https://www.ebi.ac.uk/panda/jira/browse/ENSCORESW-2690)
Alessandro made changes to both Bio::DB::HTS and ensembl-io to be able to handle empty tabix query results done on unknown seq regions. Related to 
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-3657

Update bio db hts vs

---

cpanfile

Without Bio::DB::HTS it is not possible to use e.g. VCFCollectionAdaptor. Given VCF support has to be explicitly enabled one could argue whether this is a mandatory or optional dependency, I have opted for the former because the adaptor always gets installed but have got no strict preference either way.
This is related to ENSCORESW-2717 but is by no means specific to the Ensembl VM, for example I ran into exactly the same problem while setting up a custom Ensembl environment on my workstation.
One possible problem here is that htslib detection in Bio::DB::HTS is currently somewhat fragile. It might improve soon though, I for one have submitted some PRs which address parts of the problem.

cpanfile: require Bio::DB::HTS

---

modules/Bio/EnsEMBL/Variation/DBSQL/AlleleAdaptor.pm
modules/Bio/EnsEMBL/Variation/VCFCollection.pm

-- If passed an population object make sure the method only returns data for that population
-- Don't cache if a population is given
-- separate data from VCF and database: It seems that if you fetch from database the population has to be set post object creation, however if cached array contains data from fetching from VCF all those entries are also assigned the given population

Allele adaptor master

---

modules/Bio/EnsEMBL/Variation/BaseVariationFeature.pm
modules/Bio/EnsEMBL/Variation/StructuralVariationFeature.pm
modules/Bio/EnsEMBL/Variation/Utils/Config.pm
modules/Bio/EnsEMBL/Variation/Utils/Constants.pm
modules/Bio/EnsEMBL/Variation/VariationFeature.pm
modules/t/structuralVariationFeature.t
modules/t/variationFeature.t
scripts/misc/create_config_consts.pl

`Bio::EnsEMBL::Utils::SequenceOntologyMapper` is being deprecated with https://github.com/Ensembl/ensembl/pull/246
That functionality is being replaced with Bio::EnsEMBL::Feature::feature_so_acc, and all features will be able to use that method provided they declare a constant SO_ACC.
I'm making sure all the 'features' that were supported on SequenceOntologyMapper are compliant so that pipelines that use it can be updated seamlessly.
VariationFeature and StructuralVariationFeature are some of the features that require SO_ACC.

SequenceOntologyMapper deprecation update

---

modules/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm

Handling of ORDER BY  different between MySQL 5.6 and 5.7.
Addresses issues in JIRA ENSVAR-1094
Related to:
https://github.com/Ensembl/ensembl-variation/pull/93

SQL updates for MySQL 5.7

---

modules/Bio/EnsEMBL/Variation/Pipeline/ProteinFunction/ProteinFunction_conf.pm
modules/Bio/EnsEMBL/Variation/Pipeline/ProteinFunction/RunSift.pm

Create a failure_reason table and add sift errors: Not enough sequences found by PSI-BLAST search, Less than the minimum number of sequences required.
Other problems that could be added: stack smashing detected (Could that be solved with more memory?), 100% identical with your protein query.
At the moment I'm not writing the table to file. This still needs to be done. Mouse runs very quickly and there is no benefit in discarding the md5s next release.

Sift updates

---

modules/Bio/EnsEMBL/Variation/VariationFeatureOverlap.pm

I was getting a warning from local usage of VEP, due to some lines in a VCF file  I was analysing, when using the VEP plugin "CSN".
I tracked the problem down to this bit of code. It seems that if a `VariationFeatureOverlap` does not have  a `dbID`, it is also possible that it has alleles with no `dbID`.
*) This was the warning:
`Use of uninitialized value in join or string at ensembl-vep/Bio/EnsEMBL/Variation/VariationFeatureOverlap.pm line 207, <__ANONIO__> line 4.
`
*) To reproduce, you can run vep as follows (with the CSN plugin):
```
vep --species homo_sapiens --assembly GRCh38 -i test.vcf --format vcf --pick --vcf --stats_file test.vep.vcf.html --cache --offline --fasta Homo_sapiens_assembly38.fasta --buffer_size=5000 --everything --minimal --gencode_basic --plugin CSN
```
*) Using …

fix warning from wierd edge case in VEP

---

modules/Bio/EnsEMBL/Variation/Pipeline/ProteinFunction/BaseProteinFunction.pm
modules/Bio/EnsEMBL/Variation/Pipeline/ProteinFunction/RunCADD.pm
modules/Bio/EnsEMBL/Variation/Pipeline/ProteinFunction/RunDbNSFP.pm

Codons were not reverse complemented correctly for transcripts on the reverse strand. This has been fixed now and tested against variants overlapping transcripts on reverse and forward strand and compared to dbNSFP VEP tool results.

consider transcripts on reverse strand

---

modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/DumpPopulation.pm
modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/FinishDumpPopulation.pm
modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/InitDumpPopulation.pm
modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/InitFinishDumpPopulation.pm
modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/PopulationDumps_conf.pm
modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/ReleaseDumps_conf.pm
scripts/misc/release/gvf2vcf.pl

changing up the logic of how human population dumps are generated. Human data is dumped by chromosome now. I needed to updated the generation of HapMap and ESP data dumps to join up variation information and frequencies. HapMap and ESP dumps are joined and distributed as one file per population. This won't be needed anymore if we move to only reading frequency data from VCF (next release/95?).
Also a bug fix in species naming in ftp url which was reported by Ben.

Prf94 production

---

modules/Bio/EnsEMBL/Variation/DBSQL/LDFeatureContainerAdaptor.pm
modules/Bio/EnsEMBL/Variation/VCFCollection.pm
modules/t/LDFeatureContainerAdaptor.t

We introduced looking up data from VCF files which don't have the strict_name_match flag set in the VCF config entry. This was introduced for farm species which have VCF files where the identifier is missing. I added the new code before the test if the VCF collection contained the required population which has been passed for the LD calculation. It then fails in the VCFCollection code which calls the seek method of the VCF parser when using a negative start value. I think Bio::DB::HTS should accept negative coordinates. But that would take longer to get updated because we are not in control of the repository. I also changed the order and check now first if the population is contained. Otherwise we don't need to worry about matching VCF variants to database variants.

Ld 93 strand fix

---

modules/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm
modules/t/hgvs_parser.t

If picking a transcript when a gene is supplied in a HGVS-like description, pick one where the reference matches if possible. Also handle transcript p. descriptions

HGVS parser fix

---

modules/Bio/EnsEMBL/Variation/VariationFeature.pm
modules/t/motifFeatureVariationAdaptor.t
modules/t/variationFeatureAdaptor.t

This will display motif feature variants again. missing at the moment on [staging](http://staging.ensembl.org/Homo_sapiens/Variation/Mappings?db=core;r=3:100100308-100101308;v=rs79156324;vdb=variation;vf=616739697). But the data should be back with this little tweak.

compute motif_feature_variations on the fly for human

---

sql/table.sql

Fix 2 broken links in the documentation, 'clinical significance' and 'evidence status'.

Fix broken links in documentation

---

sql/patch_95_96_b.sql
sql/table.sql

Tested on danio_rerio_varation_94_11.  variation_synonyn (n=33390).
TODO testing timing on larger table - homo_sapiens

Patch for variation_synonym release 96

---

.travis.yml

Removing dist and group from the travis file prevents the error `DBI connect('mysql_local_infile=1;port=3306;host=127.0.0.1','root',...) failed: Can't connect to MySQL server on '127.0.0.1' (111) `(https://travis-ci.org/Ensembl/ensembl-variation/jobs/469510857)

remove dist and group

---

modules/Bio/EnsEMBL/Variation/VariationFeature.pm
modules/t/hgvs_parser.t

Fix for ENSVAR-1438
Fix the HGVS where trimming of delins to an ins, gave start position larger than the end position.

Fix postion for ins in HGVS

---

scripts/import/post_import_phenotypes.pl

This came up in our health checks. Empty strings are now replaced by NULL.

replace empty string by NULL

---

modules/Bio/EnsEMBL/Variation/VariationFeature.pm
modules/t/variationFeature.t
scripts/misc/generate_vep_examples.pl

- return example rsIDs of non failed variation
- remove pileup from formats generated by default, format not supported any more
- fix a typo/bug

Fix script for generating default vep examples for WEB VEP form

---

modules/Bio/EnsEMBL/Variation/Pipeline/CheckTranscriptVariation.pm
modules/Bio/EnsEMBL/Variation/Pipeline/VariationConsequence_conf.pm
scripts/import/ImportUtils.pm

The TranscriptVariation loads file from shared directory. To prevent overwriting files, the file existence is checked before renames occur during loading. ImportUtils is used by other loading scripts and pipelines - will the die cause a problem?

Update of file checks and LSF queue for TranscriptVariation pipeline

---

modules/Bio/EnsEMBL/Variation/CADDAnnotation.pm
modules/Bio/EnsEMBL/Variation/VCFCollection.pm

This PR catches the error thrown by Bio::DB::HTS::Tabix as reported on the service channel by Emily (Request: /Homo_sapiens/Variation/Explore?db=core;v=rs17502934
Reference: 6e02dd8bc8
Error: Couldn't find index for file /nfs/public/relea). It is not confirmed if this is only for the CADD files that are read from FTP. We might need to move the files to a local directory like we do for VCF files.

catch error

---

scripts/import/import_clinvar_xml

Updated to deal with the wrong RCV record: ENSVAR-2067. 
Solution: save phenotypes only if the rsID is present in the database and don't try to create objects based on the xml locations/hgvs details.

update import clinvar

---

scripts/import/dbSNP_v2/load_dbsnp.pl

This is this the same as #382 which was on master branch.
It needs be put on postreleasefix/97 and release/97

Exclude canonical ref allele from merge and fix TOPMed

---

modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/BaseDataDumpsProcess.pm
modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/PreRunChecks.pm

For non-vertebrate dumps, we want to have a 'variation' subdirectory to be consistent with vertebrate dumps. But since the division is added to the path in the code, it is not possible to append a further subdirectory by passing parameters when initialising the pipeline. So it's necessary to add the subdirectory in the code.
This has been tested by running the pipeline to completion; the resultant directory structure is as desired.

Adding 'variation' subdirectory for non-vertebrates

---

.travis.yml

Forgot that we always use the `master` branch for ensembl-hive in Travis

Leave ensembl-hive with the branch 'master'

---

modules/Bio/EnsEMBL/Variation/DBSQL/BaseAnnotationAdaptor.pm

Web noticed a problem with retrieving plant data from http://ftp.sra.ebi.ac.uk... I checked with them and adding http to the regex solves the problem. This will go live as soon it is merged. I will create a PR against 98 branches too.

recognize http too

---

modules/t/transcriptVariationAdaptor.t

Fix for ENSVAR-2338
Also update to only use a single vf when testing store as only single vf returned by fetch_by_dbID

Updates to allow test to be run with database intact

---

scripts/import/import_variant_synonyms

There's one source 'dbSNP151' in production db that was being created in human db when importing synonyms - also, there's no human synonym data for that source in production.  
Changed code to only check for sources with synonym data.

Fix source dbSNP - different versions 

---

modules/Bio/EnsEMBL/Variation/Pipeline/VariationConsequence_conf.pm

I'm reducing the hive capacity which reduces the number of db connections. I noticed problems when running TV for opossum with hive_capacity of 150. Reducing hive_capacity to 50 solved the connection problems.

reduce hive capacity

---

modules/Bio/EnsEMBL/Variation/AlleleFeature.pm
modules/Bio/EnsEMBL/Variation/BaseVariationFeature.pm
modules/Bio/EnsEMBL/Variation/BaseVariationFeatureOverlap.pm
modules/t/alleleFeature.t
modules/t/transcriptVariationAdaptor.t
modules/t/variationFeature.t

For consequences with the same highest rank, the first alphabetically is returned.
This is a fix for JIRA ENSVAR-2119 (98) and ENSVAR-909 (99)
PR is on postreleasefix/98 and replaces #419

most_severeOverlapConsequence set alphabetically for equal ranks

---

sql/attrib_entries.sql

When I was running the CADD and dbNSFP protein function pipeline on a fresh human database for release 98 I noticed that one of the attribs was still using the old name dbnsfp_meta_svm instead of dbnsfp_meta_lr.

update dbnsfp key used by protein function pipeline

---

scripts/import/import_all_sv_data.pl
scripts/import/import_cosmic.pl
scripts/import/remove_cosmic_or_hgmd.pl

v90 will switch to using COSV id: new stable genomic identifiers, main code changes:
- COSV ids  will be the `variation.name` entries
- the other COSM identifiers + new COSN identifiers will be stored in the `variation_synonym` table

Update cosmic import

---

modules/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm
modules/t/hgvs_parser.t
modules/t/variationFeatureAdaptor.t

Fix for HGVSp parsing for reverse strand transcripts. Examples: ENSP00000270861:p.Ser285Ala & RT: 357497

fixes for reverse strand HGVSp parsing

---

modules/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm

HGVSp is failing with transcript NM because transcript has to be fetched by external name (example NM_000088.3:p.Val1374Ala) 
http://rest.ensembl.org/variant_recoder/human/NM_000088.3:p.Val1374Ala?content-type=application/json 
Test: http://ebi-cli-003:3000/variant_recoder/human/NM_000088.3:p.Val1374Ala?content-type=application/json

Fix HGVSp when using 'NM' transcript 

---

modules/Bio/EnsEMBL/Variation/Utils/VariationEffect.pm

SVs don't have an allele string and a warning was printed for uninitialised value in comparison in the start_retained_variant  predicate. I create the same PR for postreleasefix/100.

check that allele string exists

---

modules/Bio/EnsEMBL/Variation/VariationFeature.pm

Removing the check if the species is human ensures that motif_feature_variants are no longer calculated on the fly. https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-2860

stop calculating mfv on the fly

---

modules/Bio/EnsEMBL/Variation/Pipeline/TranscriptEffect.pm
modules/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm
modules/Bio/EnsEMBL/Variation/Utils/VariationEffect.pm
modules/t/variation_effect.t

Shifting code has led to multiple occasions where consequence types within the transcript variation table can be empty. This tidies up many of these:
1) modules/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm - Prevents shifting for allele strings labelled INSERTION, DELETION, HGMD, COSMIC & CNV
2) Includes variants that start off outside of upstream and shifted into it as upstream
3) Doesn't print variants that return no consequences and are further than the given max_distance away from the transcript (i.e. variants that are shifted out of downstream)
This wont clear up all empty consequences. There are still issues with multi-allelic variants where the second alt allele is shifted into/out of protein_coding regions, but there's no quick fix for that one, so it's likely to be 101.

Clear up empty consequences

---

modules/Bio/EnsEMBL/Variation/DBSQL/TranscriptVariationAdaptor.pm
modules/t/transcriptVariationAdaptor.t

For JIRA ENSVAR-2984
Example: rs1162918467 displays null 
Tested on sandbox
http://ves-hx2-76.ebi.ac.uk:5050/Homo_sapiens/Variation/Explore?r=13:25147558-25148562;v=rs1162918467;vdb=variation;vf=493401453

Handle missing  HGVSg in TranscriptVariation  

---

modules/Bio/EnsEMBL/Variation/DBSQL/BaseAnnotationAdaptor.pm
modules/t/annotationAdaptor.t

This is to prevent throwing an error on the variant page if we cannot connect to the ftp location. IT is working on my [sandbox](http://ves-hx2-76.ebi.ac.uk:5040/Homo_sapiens/Variation/Population?db=core;r=1:230709548-230710548;v=rs699;vdb=variation;vf=179). Failing on live [site](https://www.ensembl.org/Homo_sapiens/Variation/Explore?db=core;r=1:230709548-230710548;v=rs699;vdb=variation;vf=179).

only warn at ftp connect error

---

scripts/import/import_hgmd.pl
scripts/import/map_hgmd_coord.pl

Avoid updating the variation class attrib id after the variation was inserted, ENSVAR-2583:
- move functionality add_attrib method from import_hgmd to map_hgmd_coord, renamed method to add_class_attrib_id method
- tidy a variable name : rename $vdb2  -> $vdb

Update hgmd for e101

---

modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json

After DC migration we can revert to using  ftp.ensembl.org URL

revert after datacentre move

---

modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json

Configure Gambian Genome Variation Project data. Here is a script which retrieves allele frequencies for a variant: /nfs/production/panda/ensembl/variation/anj/frequencies_from_vcf.pl
It will return frequencies for new GGVP populations.
Config updates have also been tested on my sandbox.

add configuration for GGVP data

---

modules/Bio/EnsEMBL/Variation/VCFCollection.pm

When a VCF open failed, undef was being pushed onto the close list.
At some point in the future, possibly in some other request, when
there were too many files open the code would attempt to close undef
causing an error and crashing that (possibly unrelated) request.
The code which was ultimately erroring as a result of this is just above
the diff, in the same method, lines 1250-1252.
Secondarily, better warning identifying which file open failed
when reporting failure.
(The bug which caused this many erroneous opens in the first place
has been separately identified and fixed in the webteam SOPs).

Only push VCF files-to-later-close onto list if successfully opened.

---

modules/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm

Skips the attr tests if it's an ENST transcript. 
No test has been added as no output should have changed, should only provide a minor speedup

Dont check transcript attributes if ENST transcript

---

modules/Bio/EnsEMBL/Variation/DBSQL/PhenotypeAdaptor.pm
modules/t/phenotypeAdaptor.t

By default a new Phenotype object is created with the class_attrib (trait) but not the corresponding class_attrib_id. 
The class_attrib_id should be fetch before store if it's not present.

Fix PhenotypeAdaptor store for new Phenotypes

---

modules/Bio/EnsEMBL/Variation/Pipeline/AncestralAlleles/AncestralAlleles_conf.pm

I decided not add species and assembly because for all non human species for which we can compute ancestral alleles we can run the pipeline together. We can add more information into the pipeline_name parameter if needed.

update hive dbname

---

modules/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm
scripts/import/clinvar_post_process.pl
scripts/import/import_clinvar_xml

- add functionality to match based on location and alleles existing rsIDs in the DB for RCVs without rsIDs
- update clean option to remove previously imported variation/variation_feature from ClinVar
- add try/catch for update sql warnings
- don't store risk_alleles with length > 255: they were being truncated
- handle clinsigs not present in the variation clinsig defined set

Update clinvar import

---

modules/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm
modules/t/hgvs_parser.t

ENSVAR-2536
g.99982241_99982242ins56 returns `input: "NC_000013.11:g.99982241_99982242ins56"` -> this insertion is incomplete and should throw a message. 
This PR extends an existing check to include this example.

HGVS insertion with incomplete description is not supported

---

modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json

Because of problems with igsr FTP site it was decided to move files to the ensembl ftp site.
The files have already been copied to ../ensemblftp/data_files/homo_sapiens/GRCh38/variation_genotype/ggvp
We need to wait for the files to be synced before we can merge this PR. PRs for 102 and 103 are coming too.

move ggvp data to ensembl ftp

---

modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json

Updated based on compara data:
mysql-ens-compara-prod-1 ensembl_compara_master --table -e 'SELECT name, first_release, last_release FROM method_link_species_set WHERE method_link_id = 501 AND first_release IS NOT NULL AND first_release <= 103 AND (last_release IS NULL OR last_release >= 103)'
+-------------------------------------------------+---------------+--------------+
| name                                            | first_release | last_release |
+-------------------------------------------------+---------------+--------------+
| 16 pig breeds GERP Conservation Scores          |           103 |         NULL |
| 90 eutherian mammals GERP Conservation Scores   |           103 |         NULL |
| 27 sauropsids GERP Conservation Scores          |           103 |         NULL |
| 65 …

update gerp score filenames

---

modules/Bio/EnsEMBL/Variation/Pipeline/ProteinFunction/RunSift.pm

Method run in class Bio::EnsEMBL::Variation::Pipeline::ProteinFunction::RunSift checks that $blastdb file actually exists before running. However, sometimes that file is compressed as BLASTP actually does not use it. A work around is to check that $blastdb* files exists on the same location, which would include both the original FASTA file and the files resulting from running makeblastdb.
This code has been tested while running the SIFT pipeline for maize for release 104 with help from @at7 , using 
/nfs/production/panda/ensemblgenomes/data/blastdb/uniref90.fasta

RunSift->run() checks also for blastdb* files

---

modules/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm
modules/t/variationFeatureAdaptor.t

Mouse `NC_000068.8:3115317:T:C` fetches the sequence from GRCm38 instead of GRCm39 because fetch_by_spdi_notation doesn't use the sequence version. 
Ticket: ENSVAR-3947

SPDI uses the sequence version number

---

modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/BasePhenotypeAnnotation.pm
modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/CheckPhenotypeAnnotation.pm
modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/FinishPhenotypeAnnotation.pm
modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportAnimalQTL.pm
modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportCGC.pm
modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportDDG2P.pm
modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportEGA.pm
modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportGWAS.pm
modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportHuman.pm
modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportIMPC.pm
modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportMGI.pm
modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportMIMmorbid.pm
modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportMouse.pm
modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportOMIA.pm
modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportOrphanet.pm
modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportRGD.pm
modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportZFIN.pm
modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/OntologyMapping.pm
modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/PhenotypeAnnotation_conf.pm

- fix required for GWAS e104 37 import: commit 'skip empty phenotype gwas'
- remove caching  of db adaptor
- update default dir: ENSVAR-3745
- review input ids, don't use overflow: ENSVAR-3666
- add source specific check: ENSVAR-3752
- remove old import before fresh import: ENSVAR-3746
- save genome assembly in internal production db: ENSVAR-3917

Update phenotype hive import - e104

---

sql/foreign_keys.sql

The FK datacheck picks up the relationship from sql/foreign_keys.sql. The DCs end up doing a JOIN between a value (attrib.attrib_id) and a set value (variation_citation.data_source_attrib) which is incorrect. 
Related tickets: ENSVAR-1996 and ENSVAR-3980

SQL Foreign keys - remove variation_citation attrib_id 

---

scripts/misc/generate_population_table.pl

-- the new EVA species has populations that are neither sub nor super population. The check in line 232 ensures that such populations are listed not as a sub population anymore (e.g. Gotland_Sweden)
-- there are also some populations that don't have any individuals in the population table (Hungary, Super-population from EVA study PRJEB24964) and should not be displayed at all (line 222) I create a jira ticket to look into this and then after cleaning up the database for 105 also remove the check from this script.
-- jira ticket ENSVAR-4056

fix display for new eva species

---

modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json

we need to remove the old version. The generate population table script reads studies from the vcf config and if we keep the old version of gnomAD it will also appear in the docs which we don't want.

remove old version of gnomADe GRCh38

---

modules/t/variation.t

The variation synonyms test fails in Perl 5.26 because the synonyms output order is different  `Archive dbSNP: rs17765152,rs60739517` instead of `Archive dbSNP: rs60739517,rs17765152` (other Perl versions) . To avoid this failure, need to update the test.

Update variation synonyms test

---

modules/Bio/EnsEMBL/Variation/Pipeline/Remapping/Remapping_conf.pm

HI @at7 , while remapping the previous variation to the new contiguous barley (_Hordeum vulgare_) assembly all run_mapping jobs ran out of memory. Selecting the extra_mem resource class solve the problem.

added extra_mem resource class to Remapping_conf.pm

---

scripts/import/import_EPMC.pl

Format authors to store the first 4 authors. If longer than 4, include 'et al'. 
ENSVAR-4182

Citations import - format authors

---

modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/BasePhenotypeAnnotation.pm

The MySQL servers are using strict SQL.
This fixes SQL errors raised
- extra commas in insert to set values
- truncation of string larger than table.field where stored
For further detail see: ENSVAR-4193
In the shorter term tests should be added to trim_value_string and moved to a utility module
In the longer term the fields being truncated will be remodelled

Phenotype Annotation Fixes for strict SQL

---

scripts/misc/generate_population_table.pl

The bug fix can be reverted now that the empty populations have been remove from the parus major database.
https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4056

after removing empty populations remove check for parus major

---

scripts/import/import_all_sv_data.pl

SV import was inserting duplicated values in SET `clinical_significance`. This is not possible anymore because the servers are using strict SQL.

Update Structural variants import (strict SQL)

---

modules/Bio/EnsEMBL/Variation/Utils/Sequence.pm
modules/t/sequence_utils.t

Method to generate GA4GH VRS Allele from SPDI.
To be used in Variant Recoder and VEP
For further info see: ENSVAR-4092, ENSVAR-4186

Generate GA4GH VRS Allele from SPDI

---

modules/Bio/EnsEMBL/Variation/BaseTranscriptVariationAllele.pm
modules/Bio/EnsEMBL/Variation/Utils/Config.pm
modules/Bio/EnsEMBL/Variation/Utils/Constants.pm
modules/Bio/EnsEMBL/Variation/Utils/VariationEffect.pm
modules/t/variation_effect.t

Adds the new consequences:
- splice_donor_5th_base_variant (SO:0001787) 
- splice_donor_region_variant (SO:0002170) 
- splice_polypyrimidine_tract_variant (SO:0002169 )
into the main VEP code. Currently, they can be added through the SpliceRegion plugin.

Adds SpliceRegion Consequences to main VEP

---

scripts/misc/mart_variation_effect.pl

Use `Bio::EnsEMBL::DBSQL::DBConnection` instead of `DBI` when loading from a file dump. Similar to #751

Change mart_variation_effect.pl to use DBConnection

---

modules/Bio/EnsEMBL/Variation/MotifFeatureVariationAllele.pm

Running the funcgen pipeline on codon was causing errors when mf_start was < 1. Returning undef for those cases fixed the error.

catch case where mf_start is negative

---

scripts/import/import_all_sv_data.pl

Update message to display correct temp tables name 'temp_sv' and 'temp_sv_phenotype'.

Structural variants import - fix tables name in message

---

sql/patch_106_107_c.sql
sql/table.sql

Patch to remove the spurious consequences from transcript_variation table.
Tested on copy of dog DB and works.

DB patch remove incorrect transcript_variation consequences

---

modules/Bio/EnsEMBL/Variation/Utils/BaseVepTabixPlugin.pm

This pull request is part of [CADD](https://github.com/Ensembl/VEP_plugins/pull/470) header refactor. Basically, it's necessary to give "$file" (filename) as input to `parse_data()`.
1) Make sure all vep plugins are not affected by this new attribute.

refactor: Add filename to parse_data input

---

modules/Bio/EnsEMBL/Variation/Utils/BaseVepTabixPlugin.pm

Added function documentation based on that available for [BaseVepPlugin.pm](https://github.com/Ensembl/ensembl-variation/blob/release/105/modules/Bio/EnsEMBL/Variation/Utils/BaseVepPlugin.pm) and [BaseVepFilterPlugin.pm](https://github.com/Ensembl/ensembl-variation/blob/release/105/modules/Bio/EnsEMBL/Variation/Utils/BaseVepFilterPlugin.pm). Also edited the synopsis to better reflect the use of BaseVepTabixPlugin.pm and added a couple of inline comments.
Tested and working with perldoc 3.28

Add function documentation to BaseVepTabixPlugin.pm

---

scripts/import/import_EPMC.pl

The citations not found in db are written to a text file. This file should have the same format as the input file (source EPMC):
refsnp,PMCID,EXTID,SOURCE

Update citations import (107)

---

modules/Bio/EnsEMBL/Variation/Pipeline/DBSNPImport/DBSNPImport_conf.pm
scripts/import/dbSNP_v2/init_load_dbsnp.pl
scripts/import/dbSNP_v2/load_dbsnp.pl

JIRA [ENSVAR-4677](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4677)
@helensch added a few alterations (https://github.com/Ensembl/ensembl-variation/pull/789) to `load_dbsnp.pl`. This PR updates OPTIONS adding add_maf to command description and also truncate minor_allele in case of minor allele is bigger than 50bp.
1. Run `load_dbsnp.pl` with `--add_maf` flag. Make sure it has a minor_allele, i.e
```sh
2022-03-29 09:43:42     rs55689549      truncated_minor_allele  rsid=rs55689549;minor_allele=ATTTAATTATTAATTAAATAATTTAATTTATTTATTATTATAAATTTATTAATATAAATTAAATA
2022-03-29 09:45:04     rs67288656      truncated_minor_allele  rsid=rs67288656;minor_allele=TTCTTAGGATGGCTCTGTATTCATTATGGATTTCATAAGTCACATGGCTGGAAGGTACCTGATA
2022-03-29 09:45:05     rs67673721      truncated_minor_allele …
```

feat: Add truncation in minor_allele exception + OPTIONS

---

README.md
tools/linkage_disequilibrium/README.md
travisci/trigger-dependent-build.sh

Renaming master to main for files dependent on `ensembl-variation` repo
For file, travisci/trigger-dependent-build.sh, there are some inconsistent lines as ensembl-rest is on main and ensembl-vep is on master. For now, keeping them the same and updating them after `ensembl-vep` is renamed to main

Renaming master to main

---

scripts/misc/update_match_seq_region_ids.pl
scripts/misc/update_seq_region_coord.pl

During transcript variation pipeline, `seq_region_id` throughout tables need to be aligned (Core DB vs. Variation DB). This PR adds a script to check all `seq_region_id` and update if necessary those IDs based on core database.
1) Run script with `--dry_run` flag to check all updates this script would make.
2) Run without `--dry_run` flag.

feat: Add update_match_seq_region_ids.pl

---

scripts/export/dump_GO_terms.pl

* GO files are only dumped for species for which there are variation databases
* _Monodelphis domestica_ is skipped for its large genome size (Tabix is limited to chromosomes with 512 Mbp or less)
GO files can be dumped as defined in the Confluence page: [Dump GO terms](https://www.ebi.ac.uk/seqdb/confluence/display/EV/Dump+GO+terms)

Dump GFF files from GO plugin

---

modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json

We are adding new genotype data from EVA vcf - 
https://www.ebi.ac.uk/eva/?eva-study=PRJEB44919 
In this process we need to update the vcf file information in the vcf_config.json file. The genotype data is tested on sandbox - 
e.g. - http://wp-np2-11.ebi.ac.uk:7070/Gallus_gallus/Variation/Population?db=core;r=1:196051926-196053237;v=rs739477247;vdb=variation;vf=4893594)

Update json configuration for new genotype data

---

modules/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm

Jira: [Card](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4859)
An user (https://github.com/Ensembl/ensembl-vep/issues/812) found out that while we are using VEP output from CADD is incomplete. This PR fix absence of CADD results while using --hgvs or --hgvsp
* When `hgvs_protein` function in `TranscriptVariationAllele.pm` tries to output hgvs_protein string, several alterations are made in $vfoa object. HGVS alterations might alter any --custom / --plugin outputs since these flags are launched after hgvsp output.
* It can be important to look up if `--hgvs` flag might alter other output that use` $vfoa`.
1) Try annotate VCF with `--hgvs` using or not this PR, use for example:
```sh
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NA12878_58
chr1    78024345 …
```

fix: CADD while using --hgvs flag

---

modules/Bio/EnsEMBL/Variation/VariationFeature.pm
modules/t/variationFeature.t

Jira: [Card](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4727)
As reported by issue https://github.com/Ensembl/ensembl-vep/issues/1120, flag `--spdi` is not working at all. Before we have more definitive solution, this PR enables output be created without synonyms.
1) Run vep with `--spdi` flag with and without this branch;
Old error:
```sh
Can't call method "db" on an undefined value at /<PATH-TO>/ensembl/modules/Bio/EnsEMBL/Slice.pm line 2984, <$fh> line 54.
```
This error should disappear and INFO field `SPDI` being populated, i.e: `21:6116502:C:T`
PS.: #809 Reopening due to revert error

fix: --spdi flag quick fix

---

modules/Bio/EnsEMBL/Variation/VariationFeature.pm
modules/t/variationFeature.t

It seems that we need to keep get_all_synonyms() in case adaptor->db still exists.
1) Run VEP with --spdi flag

fix: spdi --flag keep get_all_synonyms()

---

.travis.yml
modules/t/alleleAdaptor.t

`travis.yml` should always get `main` branch from `ensembl-hive` no matter the value of `$ENSEMBL_BRANCH`. This small change reinforces that idea and reflects our [internal docs](https://www.ebi.ac.uk/seqdb/confluence/display/EV/Release+coordination#Releasecoordination-ensembl-variation).

Fix: facilitate updating `.travis.yml`

---

scripts/export/dump_GO_terms.pl

The human assembly in Web VEP should be GRCh37 / GRCh38, unlike the assembly in CLI (37 / 38, respectively). As such, when dumping GO terms for humans, we need to manually add the prefix, like done by the script to dump Phenotypes GFF files.

Fix Human GO dump filenames for web VEP

---

modules/Bio/EnsEMBL/Variation/VCFCollection.pm

When getting the vcf file object we should also check if the synonym of the chromosome (or seq region) of interest matches what we have in the file or in the `chromosomes` list (if mentioned in the vcf config file). It will be checked only if `use_seq_region_synonyms` option is set in the vcf config file.
This is particularly helpful when we have large set of synonyms in the vcf file and mentioning their corresponding seq region in the `chromosomes` list is not feasible/pretty (e.g. -  pike perch in rapid release and pangenomes). In case the synonyms list is small their corresponding seq region can be mentioned in the `chromosomes` list in vcf config (see rabbit in main site). This extra check does not break this behavior.
Tested with 4 species in rapid release - 
pike perch
Crab-eating …

Check also synonyms when getting vcf file object

---

modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json

JIRA: [Card](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4965)
Add support for remote EVA variants from Collared Flycatcher (Ficedula Albicollis).
Just check if structure fits and public-plugins PR is already merged (https://github.com/Ensembl/public-plugins/pull/574)

feat: Add ficedula albicollis to vcf_config.json

---

modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json

[ENSVAR-4962](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4962)
Added support for Great tit (Parus_major)
Sandbox: http://wp-np2-11.ebi.ac.uk:6070/Parus_major/Location/View?r=2:71746274-71844284
[ENSVAR-4963](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4963)
Added support for Japanese quail (Coturnix_japonica)
Sandbox: http://wp-np2-11.ebi.ac.uk:6070/Coturnix_japonica/Location/View?r=3:71823736-72447687

Add great-tit and japanese-quail EVA variants (108)

---

scripts/import/import_all_sv_data.pl

There is a phenotype description that includes a comma but the comma is being used to split different phenotypes. 
Phenotype example:
`2,4-Dienoyl-CoA Reductase Deficiency`

Update structural variation import (109)

---

modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json

Add support for remote EVA variants from Pike-perch (_Sander lucioperca_).
Check first Ensembl/public-plugins#582

Add pike-perch EVA variants

---

scripts/misc/generate_vep_examples.pl

By using a registry file, we can provide databases from multiple hosts (specially useful for species with VCF backends).
Other changes:
* Remove warnings when certain types of IDs are not defined
* Usage documentation via `-help`
* Raise error when no Ensembl version is provided
* Check if the help documentation seems reasonable
* Create an ensembl.registry file and check if it works:
```
#!/usr/bin/perl
use Bio::EnsEMBL::Variation::DBSQL::DBAdaptor;
use Bio::EnsEMBL::Registry;
Bio::EnsEMBL::DBSQL::DBAdaptor->new
( '-species' => "microtus_ochrogaster",
'-port'    => 4519,
'-host'    => 'mysql-ens-sta-1',
'-user'    => 'ensro',
'-pass'    => '',
'-dbname'  => 'microtus_ochrogaster_core_108_10'
);
Bio::EnsEMBL::Variation::DBSQL::DBAdaptor->new
( '-species' => "microtus_ochrogaster",
'-port' …
```

Generate VEP examples using registry file

---

modules/Bio/EnsEMBL/Variation/Pipeline/GeneFactory.pm
modules/Bio/EnsEMBL/Variation/Pipeline/LoadWebIndexFiles.pm
modules/Bio/EnsEMBL/Variation/Pipeline/VariationConsequence_conf.pm

Datachecks pointed out that we have non-existent variation_id from variation table in variation_hgvs table. I.e,
```sh
variation_id	hgvs_name	variation_id	source_id	name	flipped	class_attrib_id	somatic	minor_allele	minor_allele_freq	minor_allele_count	clinical_significance	evidence_attribs	display
741221451	c.110+4G>T	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL
741221451	c.212-1690G>T	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL
741221451	c.700+4G>T	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL
741221451	n.1800G>T	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL
741221452	n.124_125insACGTAGACATTCCT	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL
741221452	n.125_126insACGTAGACATTCCT	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL …
```

fix: variation_hgvs table missing values

---

modules/Bio/EnsEMBL/Variation/Pipeline/GeneFactory.pm
modules/Bio/EnsEMBL/Variation/Pipeline/UpdateVariationFeature.pm

Jira: [Card](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5019)
As reported by Jamie, we had a few transcripts that were not deleted during update mode for VariationConsequence Pipeline. This PR divides `DELETE FROM` command in smaller chunks similar to UpdateVariationFeature task to avoid any long string problem.
1) Running VariationConsequence Pipeline and checking after `GeneFactory` if all deleted transcripts were removed.

fix: Delete from GeneFactory in smaller chunks

---

modules/Bio/EnsEMBL/Variation/BaseAnnotation.pm
modules/Bio/EnsEMBL/Variation/DBSQL/VCFCollectionAdaptor.pm
modules/Bio/EnsEMBL/Variation/VCFCollection.pm
modules/t/VCFCollection.t
modules/t/vcf_config.json

[ENSVAR-4961](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4961)
This PR attempts to add a boolean flag to VCF config file that allows fetching consequences from VCF file instead of calculating on fly
This flag is then used to set dont_fetch_vf_overlaps in get_all_VariationFeatures_by_Slice in https://github.com/Ensembl/ensembl-webcode/blob/78c0e72a29ee87ea9e2ee9f2981a95cccb49cb34/modules/EnsEMBL/Web/Query/GlyphSet/Variation.pm#L236

Add a boolean flag in VCF config to fetch consequences from VCF file

---

modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json

The study we used to point to at the EVA contains a load of genotyping info that we’ll lose by pointing to the new VCF.
This PR restores the config to point to the original VCF

Restoring config for parus_major to use the original VCF

---

modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json

Just need to rename subfolder to a standard convention.

fix: Renaming sus_scrofa subfolder to conventional

---

modules/Bio/EnsEMBL/Variation/Pipeline/VariationConsequence_conf.pm

When running full mode, I noticed that rebuilding indexes was not working properly. This PR fix workflow logic to run properly index rebuild after running web_index_load
1) Just need to check that rebuild indexes is triggered by init_transcript_effect as previsouly.

fix: Rebuild indexes not working in normal mode

---

modules/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm

For some transcripts the version can be undefined and can cause warning when appending to stable id / hgvs reference. For example, (for yeast) YDL149W_mRNA.
This got caught while running IntAct plugin. An example command to reproduce the issue - 
```
PLENV_VERSION=5.14.4 perl /hps/software/users/ensembl/repositories/snhossain/ensembl-vep/vep --i ../data/test_yeast --o ../output/out_intact.txt --fork 4 --database --db_version 107 --force_overwrite --hgvs --plugin IntAct,feature_ac=1,mutation_file=/hps/nobackup/flicek/ensembl/variation/snhossain/issues/ensvar-3250/data/mutations.tsv,mapping_file=/hps/nobackup/flicek/ensembl/variation/snhossain/issues/ensvar-3250/data/rat/mutation_gc_remap.txt.gz --species saccharomyces_cerevisiae --assembly R64-1-1 
```
with input data - 
``` …
```

Fix warning when transcript/translation version is not defined

---

sql/attrib_entries.sql

We import more data from CGC, we need to add 3 attrib_types to store the extra data: [ENSVAR-3591](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-3591)

Add new attrib_type for CGC phenotypes

---

modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/README_GVF_human
modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/README_VCF
modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/README_VCF_human
modules/Bio/EnsEMBL/Variation/Utils/dbSNP.pm
modules/t/structuralVariation.t
modules/t/structuralVariationFeature.t
modules/t/studyAdaptor.t
modules/t/supportingStructuralVariation.t
modules/t/test-genome-DBs/homo_sapiens/variation/study.txt
scripts/import/import_all_sv_data.pl
scripts/misc/release/gvf2vcf.pl
scripts/misc/veplotyper.pl
scripts/remap_gnomad/README

This PR updates all ftp URLs from `http://` and `ftp://` protocol to https.
The affected hostnames have been tested to work with https.
Other affected repos are listed in the JIRA ticket.
Webteam JIRA ticket: https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6632
Sandbox: http://wp-np2-1d.ebi.ac.uk:1680

Update ftp links to https

---

sql/patch_109_110_a.sql
sql/patch_109_110_b.sql
sql/patch_109_110_c.sql
sql/table.sql

Schema update: sql/patch_109_110_a.sql
Add DDG2P attrib_id to variation_citation: sql/patch_109_110_b.sql ([ENSVAR-4990](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4990))
Add new clinical significance values: sql/patch_109_110_c.sql ([ENSVAR-5196](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5196))

Add patches for 110

---

modules/Bio/EnsEMBL/Variation/Utils/Config.pm
scripts/import/clinvar_post_process.pl
scripts/import/import_all_sv_data.pl
scripts/import/import_clinvar_xml

Update the supported clinical significance values in:
- ClinVar scripts
- Utils config
(Structural Variants import script is being updated in this PR https://github.com/Ensembl/ensembl-variation/pull/893)
[ENSVAR-5196](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5196)
This PR requires the patch patch_109_110_c.sql from PR: https://github.com/Ensembl/ensembl-variation/pull/896

Update clinical significance list

---

scripts/import/dbSNP_v2/sort_table_by_columns.pl

During dbSNP import sorting 1 billion row table seems to be a slow process. To enhance this task we might use a script that:
* Dump entire table;
* Sort using desired columns;
* Load entire table back into database;
This strategy were able to sort 1-billion rows table in less than 2 days, which is better if compared to +14 days using "ALTER TABLE ... ORDER BY ...".
1) Create a database with a table like variation_feature;
2) Unsort table (you might order using variation_id);
3) Run script sorting another desired columns;

feat: Create script to sort table by columns outside mySQL

---

scripts/export/release/dump_gvf.pl

If the release dump pipeline is stopped in the middle of gvf file dumping from DB and restarted again, it starts appending on the already existing file. It results in gvf file corruption.
To prevent this, check if file already there and is not empty and just delete the file before starting gvf dump all over again.

Prevent gvf file corruption in Release dump pipeline

---

modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json

[ENSVAR-4075](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4075): VCF files were remapped from sheep texel LD populations. This PR allows Sheep rambouillet to use the remapped VCF files to display LD data in web: [sandbox example](http://wp-np2-11.ebi.ac.uk:6070/Ovis_aries_rambouillet/Location/LD/ajax?db=core;r=1%3A124145-126818;pop1=153;pop2=142;pop3=132)
Related with https://github.com/Ensembl/public-plugins/pull/630

Add VCF files for LD populations in sheep Rambouillet

---

modules/Bio/EnsEMBL/Variation/Pipeline/VariationConsequencePreTasks.pm

Jira: [Card](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5255)
While running update_mode, if you set a wrong `--update_diff` filename pipeline understands that you have started a full mode wrongly. This PR creates a `die` to crash in first task to advise that user need to introduce correct name.
1) Start a VariationConsequence pipeline with `--update_diff` followed by a wrong name.
2) It should get: `File used in flag --update_diff <PATH-TO>/<FILE> does not exist`

fix: Do not run if update_diff is wrong

---

modules/Bio/EnsEMBL/Variation/Utils/Constants.pm
modules/t/variation_effect.t

During SV annotation, we are over-annotating `splice_polypyrimidine_tract_variant` in every SV that overlaps splice region related to this type of variant (+3 til +17 next to 3' acceptor_site). It was decided that when variant touches exon, it should not deliver splice_polypyrimidine_tract_variant as a term.
1) Check `splice_polypyrimidine_tract_variant` in different scenarios.
PS. coverage decreased due to commented code removal.

refactor: Avoid over-annotation of splice_polypyrimide_tract_variant

---

scripts/import/import_cosmic.pl

- Filter COSMIC import by chromosome (no need to split input file beforehand)
- When cleaning up, move tmp tables to new database with same name suffixed by `_tmptables`
Minor improvements:
- Allow to use `cosmic` argument instead of `version` to specify COSMIC version (to avoid confusing with Ensembl release version)
- Fix `cleanup` instructions
- Raise error if cleaning up without providing a registry file
- Print messages with progress of cleanup

Improve COSMIC import by chromosome and cleanup

---

scripts/import/dbSNP_v2/update_old_sets.pl

Card: [JIRA](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5097)
This script is meant to be used every new dbSNP import to update values from variation_feature.variation_set_id + "lift" old variation_set_variation table.
1) Setup a registry file with database that have new dbSNP import.
2) Make sure that host have same database name pattern with last version, i.e:
New database: homo\_sapiens\_variation\_**109**\_38 or dbSNP\_database\_test\_**109**\_38
Old database: homo\_sapiens\_variation\_**108**\_38 or dbSNP\_database\_test\_**108**\_38
3) Command-line demand:
* Registry file
* Release number
* Temp directory folder
Example: `perl <PATH-TO>/update_old_sets.pl -registry ensembl.registry -release 109 -tmp <PATH-TO-FOLDER>/`
1) Create old database with variation_feature, and new …

feat: Create update old sets script

---

nextflow/ProteinFunction/main.nf
nextflow/ProteinFunction/nf_modules/sift.nf

- Use UniRef release note file to get proper database version
- Add default paths to data for SIFT and PolyPhen-2
- Point to `ensemblorg`'s SIFT Docker image

Fix SIFT database version in SIFT/PolyPhen-2 Nextflow pipeline (e110)

---

nextflow/ProteinFunction/main.nf
nextflow/ProteinFunction/nextflow.config
nextflow/ProteinFunction/nf_modules/polyphen2.nf
nextflow/ProteinFunction/nf_modules/sift.nf
nextflow/ProteinFunction/nf_modules/translations.nf

- Add memory limits using configurable labels (like in eHive pipeline)
- Increase default `queueSize`
- Avoid Nextflow job submission issues 
- Add `submitRateLimit` to limit number of jobs sent by Nextflow to LSF
- Retry Nextflow job submission errors (`255` error code)
- Validate database input parameters
- Overwrite log/report files by default
- Generalise `nextflow.config`

Improve SIFT/PolyPhen-2 Nextflow pipeline

---

scripts/import/import_variant_synonyms

When a variant has two values in variation_feature table: 1) One with empty variation_set_id + 2) Filled variation_set_id, in current UnitProt update this will crash. This PR assumes that filled variation_set_id is the valid one and add filled + new variation_set_id in both cases.
1) Try running update with warning message and comment inserts;

fix: More generic rules to add variation_set_id

---

modules/Bio/EnsEMBL/Variation/Pipeline/ProteinFunction/InitJobs.pm

Old server uri should be of following format to avoid wrong database name being configured (e.g. `horse_variation_109_3`) - 
`mysql://[user]:[pass]@[host]:[port]/[old version]`
Needed to use password in the uri because the registry contains user with write permission to update protein function table.
Test pipeline link:
http://guihive.ebi.ac.uk:8080/versions/96/?driver=mysql&username=ensadmin&host=mysql-ens-var-prod-4&port=4694&dbname=snhossain_ehive_protein_function_109_equ_cab3.0_horse&passwd=xxxxx

Update PF pipeline to have correct old server uri

---

modules/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm
modules/Bio/EnsEMBL/Variation/VariationFeatureOverlapAllele.pm

A user reported an issue in the HGVS protein returned by the plugin ProteinSeqs ([ticket](https://github.com/Ensembl/ensembl-vep/issues/1350))
The HGVSp is not the same as the one returned by VEP.
The issue is caused by this code update: https://github.com/Ensembl/ensembl-variation/pull/814/files 
`$self->{variation_feature_seq}` is updated to store the original alt allele however this has a downstream impact -> the hgvs protein calculated by the plugin is based on the **original alt allele** but the hgvs protein calculated by VEP is calculated based on the **shifted alt allele**. 
The plugins are going to be updated to not use `variation_feature_seq`.
[ENSVAR-5501](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5501)

Update TranscriptVariationAllele - revert PR 814

---

scripts/import/import_cosmic.pl
scripts/import/remove_cosmic_or_hgmd.pl

- Put prepare statements outside `for` loop
- Flush STDOUT buffer immediately to get real-time log
- Fix cleanup of tmp tables (it was ignoring chromosomes X, Y and MT)

Improve COSMIC scripts

---

scripts/misc/update_web_vep_plugins_documentation.pl

[ENSVAR-5395](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5395): Web docs: improve VEP plugins public docs
Also made small improvements to docs of some VEP plugins: https://github.com/Ensembl/VEP_plugins/pull/573
- Make URLs clickable
- Improve display of variant location examples ([NMD](https://github.com/Ensembl/VEP_plugins/blob/release/109/NMD.pm) and [SpliceRegion](https://github.com/Ensembl/VEP_plugins/blob/release/109/SpliceRegion.pm)) by using code blocks
- Display scripts in code blocks ([EVE](https://github.com/Ensembl/VEP_plugins/blob/release/109/EVE.pm))
- Properly show common bash commands in contiguous code blocks (e.g., [MTR](https://github.com/Ensembl/VEP_plugins/blob/release/109/MTR.pm) and [LOEUF](https://github.com/Ensembl/VEP_plugins/blob/release/109/LOEUF.pm))
- …

Improve script to generate VEP plugins public docs

---

modules/Bio/EnsEMBL/Variation/BaseVariationFeatureOverlapAllele.pm
modules/Bio/EnsEMBL/Variation/Utils/Config.pm
modules/Bio/EnsEMBL/Variation/Utils/Constants.pm
modules/Bio/EnsEMBL/Variation/Utils/VariationEffect.pm

[ENSVAR-4796](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4796)
The consequence for SVs overlapping full transcripts is being calculated as **intergenic variant** (given that no other consequence is appropriate). For instance:
To avoid displaying this incorrect consequence in these cases, we opted to return [`coding_transcript_variant`](http://www.sequenceontology.org/browser/current_release/term/SO:0001968) if overlapping protein-coding transcripts or [`non_coding_transcript_variant`](http://www.sequenceontology.org/browser/current_release/term/SO:0001619), otherwise.
* Add required pre-checks predictions to structural variants with `complete_overlap`:
* `within_feature` to generalise the already existing `non_coding_transcript_variant` consequence
* `biotype` to check if transcripts …

Fix consequences for SVs overlapping full transcripts

---

scripts/import/clinvar_post_process.pl
scripts/import/import_clinvar_xml

By default, the plugin prints many messages, making it very difficult to find serious issues/errors.
This update adds most of the messages to be printed in debug mode. It also:
- updates from `|| die` to `or die`
- fix indentation
- updates method `clean_old_data`

Update clinvar import + post process scripts

---

modules/Bio/EnsEMBL/Variation/Utils/FastaSequence.pm
modules/t/fastaSequence.t

[ENSVAR-2554](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-2554): Fixes https://github.com/Ensembl/ensembl-rest/issues/397 
When using VEP with a variant located after chromosome end and a FASTA file, a long allele_string of multiple `NNNNN`s is returned for `JSON` or `VCF` output (but not `TAB` or default `VEP output`).
Similar to how VEP behaves without a FASTA file, this PR intends to return only one `N` in these situations.
The VCF (`--vcf`) and JSON (`--json`) output should be the same when using VEP with or without a FASTA file.
Example of running VEP for a variant located after chromosome end:
``` 
perl $vep --id '11:g.148657042delT' --hgvs \
--cache $cachedir --cache_version 108 --db_version 108 \
--fasta $fasta \
--vcf -o vep.vcf
```

Fix long allele_string for variant located after chromosome end

---

scripts/import/import_vcf.pl

1. Update import_vcf.pl to import all chromosomes in the same run even the chr synonyms;
2. Add option `--output_file` to write how many lines were skipped - prints warning with the total of skipped lines. This can be useful for the pipeline;
3. Add option `--sort_vf` to sort the table variation_feature after import;
4. Remove old comments;
5. Remove the progress bar prints.
6. Fix issue when reading a chromosome with semi-colon (example to test: dog)
The script was tested on LSF and SLURM.

Update script import_vcf.pl to import all types of chromosomes

---

modules/Bio/EnsEMBL/Variation/Utils/Reports.pm
scripts/import/import_all_sv_data.pl
scripts/import/import_clinvar_xml
scripts/import/import_variant_synonyms

Add a new module to report the number of rows for variation tables before and after an import.
Update:
- ClinVar
- Variation synonyms
- SVs
Ticket: ENSVAR-5524

Report number of rows before and after imports (111)

---

nextflow/ProteinFunction/nextflow.config
nextflow/ProteinFunction/nf_modules/polyphen2.nf
nextflow/ProteinFunction/nf_modules/sift.nf
nextflow/ProteinFunction/nf_modules/translations.nf

- Use increasing amounts of memory when jobs fail because of memory limits
- Retry jobs when LSF job submission fails
- Use tuples to ensure expected pair of arguments (giving two ordered arguments is not safe, as Nextflow may reorder their values when running)
- Increase default number of simultaneous jobs
- Only show jobs as failed if they effectively failed (jobs that finished successfully without output are considered successful now, although downstream jobs will not be run given that there is no output)

SIFT/PolyPhen-2 Nextflow pipeline improvements

---

modules/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm
modules/Bio/EnsEMBL/Variation/VariationFeature.pm

- [ENSVAR-5765](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5765): VEP incorrectly term HGVS type as ins when it should be dup. This happens when the variant strand is in reverse and transcript strand is forward. 
- [ENSVAR-5625](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5625): We are clipping alleles when the HGVS type is `delins` and update type and co-ordinates. We are not considering type changing to `dup` currrently. Related issue - https://github.com/Ensembl/ensembl-vep/issues/500 
- [ENSVAR-2140](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-2140): Add new argument `--hgvsp_use_prediction` to output HGVSp in prediction format. Related issue - https://github.com/Ensembl/ensembl-vep/issues/861
_Test data are in the respective JIRA tickets_

Some (more) HGVS updates

---

scripts/misc/generate_clin_significance_tables.pl

This PR allows to group similar clinical significance terms together in Variation docs.
See: http://wp-np2-11.ebi.ac.uk:6070/info/genome/variation/phenotype/phenotype_annotation.html

Variation docs: sort similar clinical significance terms together

---

modules/Bio/EnsEMBL/Variation/BaseVariationFeatureOverlapAllele.pm
modules/Bio/EnsEMBL/Variation/Utils/VariationEffect.pm

[ENSVAR-5786](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5786)
For CNVs with supporting evidence (basically those that we import from multiple sources), calculate the consequences using the supporting variants.
- If the supporting variants have `class_SO_term` as `deletion` or `loss`, treat CNV as a deletion.
- If the supporting variants have `class_SO_term` as `insertion`, `duplication` or `gain`, treat CNV as an insertion.
From my understanding, VEP does not support using CNVs with supporting variants as input, so there is no way to test them via VEP. I opened ticket [ENSVAR-5793](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5793) to support dbVar/DGVa identifiers, allowing to test this type of CNVs.
Check in my sandbox if consequences make sense for multiple CNVs with different …

Calculate CNV consequences based on supporting variants

---

modules/Bio/EnsEMBL/Variation/BaseVariationFeatureOverlapAllele.pm
modules/Bio/EnsEMBL/Variation/Utils/VariationEffect.pm

[ENSVAR-2086](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-2086) and related with Ensembl/ensembl-vep#1399
- Adds breakend predicate statements
- If a breakend position is located within a feature, VEP returns `feature_truncation` as a consequence (together with other consequences that also make sense)
This is an example output for some BND variants:
```
gnomAD_v2_BND_1_4       1:251749-258100 <BND>   ENSG00000228463 ENST00000424587 Transcript      downstream_gene_variant -       -       -       -       -       -       IMPACT=MODIFIER;DISTANCE=4915;STRAND=-1
gnomAD_v2_BND_1_4       1:251749-258100 <BND>   ENSG00000228463 ENST00000441866 Transcript      downstream_gene_variant -       -       -       -       -       -       IMPACT=MODIFIER;DISTANCE=44;STRAND=-1
gnomAD_v2_BND_1_4 …
```

Revise consequences for breakend variants

---

modules/Bio/EnsEMBL/Variation/Pipeline/DumpHGVS/DumpHGVS_conf.pm
modules/Bio/EnsEMBL/Variation/Pipeline/GetCAR/GetCAR_conf.pm

DumpHGVS default analysis_capacity increased to 500
GetCAR default analysis_capacity increased to 30

Increased default analysis_capacity for CAR pipeline

---

scripts/import/import_hgmd.pl

Two new options:
- `insert_tv`: populates transcript_variation + variation_feature consequence_types
- `assembly`: necessary when using `--insert_tv`
Runtime: a full import takes ~7h

Update HGMD script - add option to populate transcript_variation

---

modules/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm

When there is no "prefixed sequence" between ref and alt alleles that matches a warning is produced by this line -
https://github.com/Ensembl/ensembl-variation/blob/2fc4a6a5b931f4dc80266b4867cef8fb8a4b6d2e/modules/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm#L2187
The issue was introduced in this PR - https://github.com/Ensembl/ensembl-variation/pull/994
and result of using undefined `$preseq` - 
https://github.com/Ensembl/ensembl-variation/blob/2fc4a6a5b931f4dc80266b4867cef8fb8a4b6d2e/modules/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm#L2118

Fix warning when there is no pre-seq

---

modules/Bio/EnsEMBL/Variation/Pipeline/Remapping/FinishVariationFeatureQC.pm
modules/Bio/EnsEMBL/Variation/Pipeline/Remapping/RemappingVariationFeature_conf.pm
scripts/import/compress_genotypes_by_var.pl
scripts/import/post_process_variation_feature_variation_set.pl
scripts/misc/generate_vep_examples.pl
scripts/misc/update_seq_region_coord.pl

* [Update memory for variation_feature remap jobs](https://github.com/Ensembl/ensembl-variation/pull/1015/commits/bce75650ca658c6c45c63dd6f825187d0d1746c6)
* [Fix empty last line in `update_flip_features.txt`](https://github.com/Ensembl/ensembl-variation/pull/1015/commits/072fd2322a250255ffef99a7f1f3d8d5218b76ca) (`finish_variant_qc` step errors out when trying to run SQL command with empty line)
* Updates to remapping scripts:
* **update_seq_region_coord.pl:** [Fix script error related with truncate option](https://github.com/Ensembl/ensembl-variation/commit/9886a662a5f3d0138253bffce29208fb0fb7b42a)
* **compress_genotypes_by_var.pl:** [Truncate compressed_genotype_var when starting the run](https://github.com/Ensembl/ensembl-variation/commit/59ae9e7d9b579f34043effa97d88ef6199c38d95)
* …

Update remapping pipeline

---

scripts/import/import_EPMC.pl

Smartmatch is an experimental feature that throws warnings in newer versions of Perl. This PR intends to replace a smart match with an equivalent statement.

Avoid using smartmatch

---

scripts/import/import_all_sv_data.pl

- there were undefined variable in use - `$dba`; it should variation database adaptor - `$vda`
- In `post_processing_sample` we only have logic for `DGVa` study. While running the script other study generates warnings in this function. It is best to put a condition to run this function only when we are importing `DGVa`.

Fix SV import script

---

scripts/import/import_clinvar_xml

Revert: 
- https://github.com/Ensembl/ensembl-variation/pull/993
- https://github.com/Ensembl/ensembl-variation/pull/999
Tickets reverted:
- https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5483 (todo: re-open ticket)
- https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4987 (todo: re-open ticket)
- https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-501 (todo: re-open ticket)
This PR also fixes a bug affecting release/110: check if `$var_feats` is defined (lines 1112-1114)

Revert clinvar import updates

---

nextflow/MaveDB/bin/map_scores_to_variants.py
nextflow/MaveDB/nf_modules/fetch.nf

ENSVAR-5960: Ensure MaveDB VEP plugin works with regulatory data
- Fix start position for all genomic HGVS variants (zero-index position is now one-index position to conform with protein HGVS)
- Update URL for MaveDB REST endpoint (previous one is now invalid)
Note: The path to the updated plugin data is mentioned in ENSVAR-5960 and can be tested with https://github.com/Ensembl/VEP_plugins/pull/628.

Fix MaveDB plugin data creation

---

modules/Bio/EnsEMBL/Variation/Utils/VEP.pm

1. Update regex for input data detection based on VEP.
2. Create new exported function for input format detection to be used by VEP, avoiding code redundancy.
3. Accept CAID and Region input in web VEP.
The idea of this function is to check if this format is VCF: only these columns are needed to check that.
Basically, we should not check for the alternative allele here because:
- The valid characters for the alternative allele are constantly changing with new versions of the [VCF specification](https://samtools.github.io/hts-specs/VCFv4.4.pdf)
- It only checks the first line (other lines may have issues and are ignored)
- The regex may not be up-to-date (it already happened that we support a specific type of alternative allele but forgot to update the regex here)
- If the alternative …

Detect input format using VEP code

---

modules/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm

[ENSVAR-5478](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5478)
When we input an hgvs with the gene name, VEP returns output for chrY but it should be chrX.
Input
`PLCXD1:c.57_61del`

VEP handling Y PAR variants

---

modules/Bio/EnsEMBL/Variation/Pipeline/ProteinFunction/RunPolyPhen.pm
modules/Bio/EnsEMBL/Variation/Pipeline/ProteinFunction/RunSift.pm

[ENSVAR-5505](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5505)
Log expected errors from SIFT/PolyPhen-2 into eHive database and avoid throwing error at runtime.

SIFT/PPH2 eHive pipeline: ignore expected errors

---

modules/Bio/EnsEMBL/Variation/Utils/VariationEffect.pm

Fixes https://github.com/Ensembl/ensembl-vep/issues/1479
Simply ignore the `chr` prefix of breakend mates when checking if a mate is contained within an Ensembl feature.
In a future PR, we will also look into chromosome synonyms (ENSVAR-5967), such as `CM000664.2` and `NC_000002.12`.
Run VEP with the following pairs of variants, the results should be the same whether they regions have a `chr` prefix or not:
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT
2       29225144        bnd     G       G]2:42267610]   .       .       SVTYPE=BND
2       42267610        bnd     A       A]2:29225144]   .       .       SVTYPE=BND
chr2    29225144        bnd     G       G]chr2:42267610]        .       .       SVTYPE=BND
chr2    42267610        bnd     A       A]chr2:29225144] …
```

Fix breakend consequences when using `chr` prefix

---

modules/Bio/EnsEMBL/Variation/DBSQL/BaseStructuralVariationAdaptor.pm
modules/t/structuralVariationAdaptor.t

ENSVAR-5793: Required by VEP REST (POST method): https://github.com/Ensembl/ensembl-rest/pull/603

Fetch multiple SV by name list

---

modules/Bio/EnsEMBL/Variation/Utils/VariationEffect.pm
modules/t/variation_effect.t

JIRA Ticket - [ENSVAR-3154](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-3154)
Also see - https://www.ebi.ac.uk/seqdb/confluence/display/EV/VEP+-+non-standard+translation
There are some transcript that have non-ATG start, for example - gene WT1, transcript ENST00000332351. It has already been fixed to report `synonymous_variant` if the start codon is altered to an ATG (which is the normal start codon). But we should report `start_retained_variant` instead of `synonymous_variant` as it is more accurate/appropriate.
Added another function that checks the amino acid that replaces the start codon and see if is an 'ATG'.
Example command -
```
vep -i input_data --force --database
#input_data
11	32435360	rsfake	G	T
```

Add start_retained for non-ATG transcript

---

modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
scripts/docs/data_files/vcf_species_list_111.json
scripts/docs/generate_clin_significance_tables.pl
scripts/docs/generate_population_table.pl
scripts/docs/generate_variation_set_table.pl
scripts/docs/sources2html.pl
scripts/docs/species_list.pl

- add different color for billion counts in pages that list variant counts
- add chimpanzee and gibbon json in `vcf_config.json` which somehow got missed.
- add `vcf_species_list_111.json` data file
- fix syntax error in clin_significance generation script which causing failure in generating the tables.
- fix missing frequency for human in population page (because we were only checking genotype and ignoring frequency)

Update billion count icon in docs and other updates

---

modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportG2P.pm

`external_id` is used by BioMart.
When we updated to `MIM` BioMart lost G2P data.
[ENSVAR-6060](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6060)

Update phenotype pipeline - G2P replace MIM by external_id

---

modules/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm

Issue reported here: https://github.com/Ensembl/VEP_plugins/issues/655
The new variable $convert_to_three_letter is not being considered when the HGVS string is being created. The code always assumes a 3-letter representation.
In this PR the code checks if the representation is single or 3-letter and updates the string accordingly. 
This update has to be included in release/111

Fix HGVS single letter in TranscriptVariationAllele

---

scripts/docs/update_web_vep_plugins_documentation.pl

UTRannotator have Ensembl copyright but also external developer as author. (See - https://github.com/Ensembl/VEP_plugins/pull/657)
Current plugin doc creation script does not allow that. This PR removes that restriction.

Allow developer other than Ensembl as plugin author

---

modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/ReleaseDumps_conf.pm

We have an update to use FASTA and ancestral allele in the release dump pipeline from this commit -
https://github.com/Ensembl/ensembl-variation/pull/491
- The FASTA is used to query sequence instead of using DB
- The ancestral allele file is used to correct AA for indels after changing them in VCF format.
They are not mandatory parameter as only supposed to be used with human. But AA seems to be necessary as we do need correcting of AA for indels.
The location of these files can be passed to the pipeline using `data_dir` parameter. Current default value is of a noah dir - this PR updates it to the equivalent codon dir.
To be able to use this we should update the data_dir with updated files. Check updated docs here -
https://www.ebi.ac.uk/seqdb/confluence/display/EV/Dump+GVF+and+VCF+for+a+ …

Update release dump data dir from noah

---

scripts/docs/update_web_vep_plugins_documentation.pl

Requires Ensembl/VEP_plugins#674
- a83766f: Format bullet and numbered lists 
- Bullet lists are created for line starting with characters like `- ` and `* `
- Numbered lists are created for numbered patterns like `2. ` and `4) `
- Nested lists are not currently supported
- 23c5c38: Display plugin arguments in a table
- Arguments need to be in format `argument_name : description`
- The table only starts after a sentence that contains the keyword `key=value`
- 222828517: Add usage examples from `SYNOPSIS`
- 6d2712ec0: Add code block when using ` ``` ` (like in Markdown)
- 6e65ae3d0: Format text surrounded with `` ` `` or `'` as keyboard input (`<kbd>`)
- 2537dd582: Convert DOI (pattern like `doi:10.235/343`) to an URL
- 97d2793: Increase list of UNIX commands automatically recognised for …
```

Update VEP plugin documentation script

---

modules/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm

[ENSVAR-6131](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6131)
In https://github.com/Ensembl/ensembl-variation/pull/994 we added a update that will convert a `delins` to `dup`. An example can be found in the issue reported in https://github.com/Ensembl/ensembl-vep/issues/500 with example (`chr1  20978294  .  TTTTATTTATTTA  TTTTATTTATTTATTTA`). The code change was in `_clip_allele` function which is used to check after clipping alleles the type of HGVS notation changes. We introduced checking whether type changes to `dup` before checking for `ins`.
The `_clip_allele` function is used by both HGVSc and HGVSp. For HGVSp this change caused a problem as the `dup` calculation in done after `_clip_allele` - in `_check_for_peptide_duplication` function, whereas, for HGVSc it is done before. …

Bugfix - wrong HGVSp when `--shift_hgvs` is enabled

---

modules/Bio/EnsEMBL/Variation/StructuralVariationFeature.pm
modules/Bio/EnsEMBL/Variation/StructuralVariationOverlap.pm
modules/Bio/EnsEMBL/Variation/Utils/VariationEffect.pm
modules/t/structuralVariationOverlap.t

[ENSVAR-5967](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5967)
- Support chromosome synonyms in breakends
- Requires VEP setting up the new `$CHROMOSOME_SYNONYMS` global variable in Ensembl/ensembl-vep#1589
- Fix breakends getting more features than they should by using the correct feature slice
- Fix slices in unit tests

Support chromosome synonyms in breakends

---

modules/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm
modules/t/variationFeatureAdaptor.t

ENSVAR-6167
When a HGVSp like `ENSP00000346614.5:p.D237G` contains an amino acid whose codon sequence spans two exons, VEP gets the wrong reference sequence (`GAG`) instead of the expected (`GAT`):
```
MSG: Sequence translated from reference (GAG -> E) does not match input sequence (D)
``` 
This occurs because VEP is fetching the sequence from the exon and the intron, instead of skipping the intron sequence:
`GAgtaagtggcgtatgtaaaattgtcattctacacaaaaaatcacgagcagagggcaaagtgaaatcgtggctgctttatcattaattttgcatgtgcagcggagagcttgtcctttgtgctctaaatccttgctacaaacggttacataaaagatctaagaaagtggagacaaaggaaggtgggtaaagttagaaggaaaaaaagagctagaaaagtgtgcaagtcacttcatacctgaattcttgacatttgactggaattgttctgattagaccatggtcctcaaggcatttcacagttttttttaagtctgcgctgccttaggggattttatccttgagacatccactggcttaactcaagtttccttcaaaatatgtagcta …

Fix multi-exon HGVSp parsing

---

modules/Bio/EnsEMBL/Variation/Utils/VEP.pm

This PR allows the `region` format (used in REST) to support all SV types, such as:
```
INS:ME
INS:ME:ALU
DEL:ME:LINE1
```
Test this PR as part of https://github.com/Ensembl/ensembl-vep/pull/1618

Add all supported SV types to region format

---

nextflow/pangenomes/bin/create_pangenomes_annotation.py
nextflow/pangenomes/main.nf
nextflow/pangenomes/modules/annotation.nf
nextflow/pangenomes/modules/download.nf
nextflow/pangenomes/modules/test.nf
nextflow/pangenomes/modules/utils.nf
nextflow/pangenomes/nextflow.config

ENSVAR-5823: GO plugin annotations for pangenomes
ENSVAR-4744: Phenotypes plugin annotations for pangenomes
This Nextflow pipeline performs the following steps:
1. Download pangenomes data (FASTA and GTF files)
2. Generate GO/Phenotypes plugin annotations for GRCh38
3. Phenotypes only:
- Filter Phenotypes plugin annotation for 'Genes'
- Fetch lookup table between gene symbols and Ensembl identifiers from HGNC
6. Create pangenomes annotation (one for each assembly and each plugin):
- Get the GO/Phenotype info by comparing gene symbols between the GRCh38 and the pangenomes annotation
- Append info to the pangenome-specific GTFs
8. Test if plugin annotation works for each assembly using VEP
```
nextflow run -resume -profile lsf \
 ${ENSEMBL_ROOT_DIR}/ensembl-variation/nextflow/pangenomes \ …
```

Nextflow pipeline to create GO/Phenotypes annotations for pangenomes

---

scripts/docs/update_web_vep_documentation.pl

Because updating `%INCOMPATIBLE` hash and "Incompatible with" column in [vep options](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html) page are separate tasks they can get out of sync from each other. This script attempts to check which options are out of sync.
** the update is still manual.
relevant e112 updates:
https://github.com/Ensembl/ensembl-vep/pull/1642
https://github.com/Ensembl/public-plugins/pull/781
This should be part of documentation [update](https://www.ebi.ac.uk/seqdb/confluence/display/EV/Documentation+tasks#Documentationtasks-incompatible).

Add script to check for outdated incompatible options

---

scripts/import/import_clinvar_xml

Add option `-insert_tv` to populate transcript_variation and MTMP_transcript_variation.
By default, the script will not import consequences into those two tables (original behaviour).
Ticket: [ENSVAR-6285](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6285)

Add option to ClinVar to populate transcript variation

---

modules/Bio/EnsEMBL/Variation/Utils/BaseVepTabixPlugin.pm

ENSVAR-2596
Required by https://github.com/Ensembl/VEP_plugins/pull/681
Currently, Tabix-indexed data in VEP plugins when using `get_data` is retrieved in conglomerate from all the files.
This update allows to retrieve data only from a specific file by changing how the cache mechanism is created when `get_data` gets a file:
- Nothing should change if the last argument of `get_data` is not defined, so this change should not affect any plugins
- If `get_data` defines a file:
- Result cache are separated by filename
- Data is only retrieved for the specified filename
1. Test with https://github.com/Ensembl/VEP_plugins/pull/681
2. Test with any plugin that uses `get_data` function to see if its results are as expected (such as `CADD` plugin).

VEP plugins: retrieve data from specific Tabix-indexed files

---

modules/Bio/EnsEMBL/Variation/Pipeline/DumpVariationGeneName.pm
modules/Bio/EnsEMBL/Variation/Pipeline/GeneFactory.pm
modules/Bio/EnsEMBL/Variation/Pipeline/TranscriptEffect.pm
modules/Bio/EnsEMBL/Variation/Pipeline/TranscriptFactory.pm
modules/Bio/EnsEMBL/Variation/Pipeline/VariationConsequence_conf.pm

Updating variation consequence pipeline to have an option to run on only gencode primary transcripts.
Also improved the debug method to make it more useful and switched on from config.
Full details on ticket: ENSVAR-6238

updating for gencode primary

---

modules/t/test-genome-DBs/homo_sapiens/core/meta.txt
modules/t/test-genome-DBs/homo_sapiens/core/table.sql
modules/t/test-genome-DBs/homo_sapiens/funcgen/meta.txt
modules/t/test-genome-DBs/homo_sapiens/funcgen/table.sql
modules/t/test-genome-DBs/homo_sapiens/otherfeatures/meta.txt
modules/t/test-genome-DBs/homo_sapiens/otherfeatures/table.sql
modules/t/test-genome-DBs/multi/ontology/meta.txt
modules/t/test-genome-DBs/multi/ontology/table.sql

This PR patches test databases for 113:
`homo_sapiens/core`
`homo_sapiens/funcgen`
`homo_sapiens/otherfeatures `
`multi/ontology`
The patch for `homo_sapiens/variation` is already done

Patching test databases

---

nextflow/MaveDB/bin/liftover.py
nextflow/MaveDB/bin/map_scores_to_variants.py
nextflow/MaveDB/main.nf
nextflow/MaveDB/nextflow.config
nextflow/MaveDB/nf_modules/liftover.nf
nextflow/MaveDB/nf_modules/mapping.nf
nextflow/MaveDB/nf_modules/output.nf
nextflow/MaveDB/nf_modules/variant_recoder.nf

Other changes:
- Optimise configuration for SLURM (including improved memory config)
- Allow to input a registry file to lookup custom databases
- Remove duplicate lines
```
./main.nf -profile slurm -resume --mappings [folder_with_MaveDB_mappings] --registry [registry]
```
You can grab some MaveDB mappings from the URL mentioned in the JIRA ticket description: [ENSVAR-5485](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5485)

Update pipeline to support new MaveDB mapping format

---

nextflow/EVAImport/main.nf
scripts/import/import_variant_synonyms

Currently, the pipeline only works with absolute file paths. This PR allows to use relative file paths instead.
Requires https://github.com/Ensembl/ensembl-internal-variation/pull/143
Example script:
```bash
#!/bin/sh
release=113
species=ovis_aries_rambouillet
reg=$(realpath ensembl.registry)
host=$(v1-w details script)
current_ids=9940_GCA_016772045.1_current_ids.vcf.gz
merged_ids=9940_GCA_016772045.1_merged_ids.vcf.gz
dbname=ovis_aries_rambouillet_variation_113_2
old_dbname=ovis_aries_rambouillet_variation_112_2
chr_synonyms=chr_synonyms.txt
citations=rambouillet_citations_113.txt
sbatch -J EVAImport -o eva_import.out -e eva_import.err --mem 4GB --time 3-0 \
nextflow run -resume -profile slurm \
${ENSEMBL_ROOT_DIR}/ensembl-variation/nextflow/EVAImport \
--species $species \
--registry …
```

EVAImport: support relative filepaths

---

modules/Bio/EnsEMBL/Variation/Pipeline/ProteinFunction/ProteinFunction_conf.pm
modules/Bio/EnsEMBL/Variation/Utils/CADDProteinFunctionAnnotation.pm

[Link](http://guihive.ebi.ac.uk:8080/versions/96/?driver=mysql&username=ensadmin&host=mysql-ens-var-prod-4&port=4694&dbname=likhithas_ehive_protein_function_dbsnfp_113_38_homo_sapiens&passwd=xxxxx) to successful ehive pipeline

Add new cadd version to allowed versions

---

modules/Bio/EnsEMBL/Variation/StructuralVariationOverlap.pm
modules/Bio/EnsEMBL/Variation/StructuralVariationOverlapAllele.pm

Related with https://github.com/Ensembl/ensembl-vep/issues/1698
The allele number is currently undefined for breakends. This PR fixes that issue.
The reference breakend is given the allele number of 0, whereas all other breakends are given an allele number of 1 or higher.
Run breakpoint variants with VEP using `--allele_number`:
```
vep --id "chr22 29767384 . G [1:109650635[GG,[2:9650635[TT . . ." --database --force --db_version 112 --allele_number
```

Fix allele numbers for breakends

---

modules/Bio/EnsEMBL/Variation/Pipeline/VariationConsequence_conf.pm

Last time this pipeline was run in SLURM, some jobs failed when hitting the 24h limit. The slowest job took 26h, so increasing the limit to 48h would allow to future-proof the pipeline.

Variation Consequence pipeline: Increase default time limit for SLURM runs

---

nextflow/EVAImport/main.nf

Allow to match a subspecies with any available species, for instance `ovis_aries_rambouillet` with `ovis_aries`, when trying to run `run_variation_set`.

EVAImport: Fix undefined set_names for valid species

---

nextflow/Remapping/main.nf
nextflow/Remapping/modules/copy.nf
nextflow/Remapping/modules/crossmap.nf
nextflow/Remapping/nextflow.config
nextflow/utils/utils.nf

ENSVAR-6267: new pipeline to remap VCF files using CrossMap
* Output filenames are named with assembly from lookup table
* If ID is not in lookup table, keeps the original ID
* Copies files to Rapid Release FTP if `--rr_root` is defined
```bash
#!/bin/sh
#SBATCH -J 'remap-clinvar-pangenomes'
#SBATCH --time '1:00:00'
#SBATCH --mem '1G'
nextflow run -profile slurm -resume \
${ENSEMBL_ROOT_DIR}/ensembl-variation/nextflow/Remapping \
--ids input/ids.txt \
--vcf input/clinvar_20240624.vcf.gz \
--chain_dir input/chain \
--fasta_dir input/fasta
```

Add VCF remapping pipeline using CrossMap

---

nextflow/MaveDB/README.md
nextflow/MaveDB/bin/liftover.py
nextflow/MaveDB/bin/map_scores_to_variants.py
nextflow/MaveDB/main.nf
nextflow/MaveDB/nf_modules/fetch.nf
nextflow/MaveDB/nf_modules/liftover.nf
nextflow/MaveDB/nf_modules/mapping.nf
nextflow/MaveDB/nf_modules/utils.nf
nextflow/MaveDB/nf_modules/variant_recoder.nf
nextflow/MaveDB/subworkflows/filter.nf
nextflow/MaveDB/subworkflows/split.nf

- Accept a file containing a list of URNs (`--urn`) instead of multiple mappings files (`--mappings`)
- Automate downloading MaveDB mappings
- Correctly parse mappings from MaveDB API
- Download MaveDB metadata (before, it was included in the MaveDB mappings file)
- Download MaveDB scores in obvious processes (instead of in the middle of scripts)
- Update README instructions + diagram
Run pipeline using a file with some MaveDB URNs, such as:
```
urn:mavedb:00000001-a-1
urn:mavedb:00000001-b-1
urn:mavedb:00000001-b-2
urn:mavedb:00000002-a-1
urn:mavedb:00000003-a-1
urn:mavedb:00000003-b-1
```

Automate downloading MaveDB mappings

---

nextflow/Remapping/modules/copy.nf
nextflow/Remapping/modules/crossmap.nf

- Always run process to confirm the files were copied (avoids caching)
- Add/update CHECKSUMS
- Update time limit

Remapping pipeline: add CHECKSUMS to Rapid Release FTP

---

modules/Bio/EnsEMBL/Variation/Utils/VEP.pm

If we have a variant described at the start of a sequence it will fail for default VEP input format. For example, for a variant -
```
HSCHR15_4_CTG8	1	0	-/TC	+	var
```
The line `$line[2] && $line[2] =~ /^\d+$/ &&` will fail because the end position is `0` which is interpreted as False. We should use `exists` function instead to check if we have a field present.

Fix format checking for variant at start of a seq region

---

scripts/import/import_clinvar_xml

Ticket: https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5941
This PR includes:
- update to new format: `/ReleaseSet/ClinVarSet/ReferenceClinVarAssertion/ClinicalSignificance` updated to `/ReleaseSet/ClinVarSet/ReferenceClinVarAssertion/Classifications/GermlineClassification`
- skip when variant has clinical significance "no classifications from unflagged records"
- remove method to extract extra citations
- fix code for conflicting clinical significance
Next step is to support somatic clinical significance which is going to be done in a separate PR.

Update ClinVar format part 1

---

scripts/export/dump_GO_terms.pl

The GO plugin is printing warnings related with the `match` parameter not being defined when running the GO dumps script.
This PR fixes the issue.

GO plugin: avoid GO file dump `match` warnings

---

scripts/docs/generate_population_table.pl

Updating broken population url with working ones. They are used on the public documentations.

Fix some population url for public docs

---

modules/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm
modules/Bio/EnsEMBL/Variation/VariationFeature.pm
modules/t/transcriptVariationAdaptor.t

Ticket: https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4493
This PR fixes the alleles for HGVS coding.
It adds `invalid_alleles` if ref == alt (to be used in ensembl-vep).

Fix hgvs coding refseq mismatch

---

nextflow/EVAImport/main.nf
scripts/import/import_set_from_file.pl
scripts/import/import_vcf.pl

* Fix version, url and data types when importing EVA data
- Add new parameters `--url` and `--data_types`
- Require `--version` as a mandatory, non-null parameter
* Avoid duplicate code
* Print command in a more readable format
* Fix wrong registry file used for `import_set_from_file.pl` and `import_vcf.pl`:
- Support relative registry file paths
Run the pipeline with new options `--version`, `--url` and `--data_types` and check if the EVA information in the `source` table seems okay.
Please ask me for data to test the pipeline with.

EVAImport pipeline: fix EVA source version, url and data types

---

modules/Bio/EnsEMBL/Variation/VariationFeature.pm

Fixes Ensembl/ensembl-vep#1653
When using multiple alternative alleles with the `--hgvsg` option in VEP, the HGVSg is incorrect and different compared to running VEP on each alternative allele separately.
The bug occurs because we check the variation class SO term based on the complete allele string. In the case of an allele string with multiple alternative alleles (e.g., `GG/-/G`), we need to check the class SO term for each alternative allele separately.
Run VEP on GRCh37 with `--hgvsg`. Example variants:
```
chr8 143694490 143694490 T/TT/TTT +
chr8 143694490 143694492 GGG/GG/G +
chr14 103576804 103576805 GG/-/G +
chr14 103576804 103576805 GG/- +
chr14 103576804 103576805 GG/G +
```
The HGVSg for each alternative allele should be:
- `GG/-`: `chr14:g.103576811_103576812del` 
- `GG/G`: …

Fix HGVSg for multiple alternative alleles

---

nextflow/EVAImport/main.nf
nextflow/MaveDB/main.nf
nextflow/ProteinFunction/main.nf
nextflow/Remapping/main.nf
nextflow/pangenomes/main.nf
nextflow/utils/utils.nf

* Throw error if memory used for Nextflow head node is lower than a minimum value
- JVM memory is 1/4 of the SLURM job memory by default
- The default minimum value of 0.4 GiB is a bit lower than 1/4 of a 2 GiB SLURM job
- The error instructions show easy solutions for the issue
* Uniformise all pipelines to use common functions

Nextflow: print instructions if JVM memory is low

---

modules/Bio/EnsEMBL/Variation/VariationFeature.pm

Here https://github.com/Ensembl/ensembl-variation/pull/1077 we have fixed hgvsg for multi-allelic variant. But it introduced a bug for insertion types.
We are not sending the end position during trimming -
https://github.com/nuno-agostinho/ensembl-variation/blob/3ed1013c5bfacb2416db9e67d50cb96fb2fcb0b6/modules/Bio/EnsEMBL/Variation/VariationFeature.pm#L1970
What it does for insertion is that it increase the end position by `length of reference sequence -1` - 
https://github.com/nuno-agostinho/ensembl-variation/blob/3ed1013c5bfacb2416db9e67d50cb96fb2fcb0b6/modules/Bio/EnsEMBL/Variation/Utils/Sequence.pm#L970
This becomes problematic if the `length of reference sequence -1` is not the same as `end - start` and there is no trimming happening so that position sticks around. This happen only …

Fix hgvsg for insertion with ref allele `-`

---

modules/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm

In this PR https://github.com/Ensembl/ensembl-variation/pull/1103/files the HGVSc was updated to reflect the alleles used in the annotation after a refseq editing. 
Original ticket: https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4493
This PR fixes the alleles to be represented relative to the transcript.
It also fixes one of the issues reported here https://github.com/Ensembl/ensembl-vep/issues/1775

HGVSc for RefSeq transcripts - represent the alleles relative to the feature

---

modules/Bio/EnsEMBL/Variation/Pipeline/VariationConsequence_conf.pm

It was announced the 2.6 branch doesn't have Slurm support (officially) and is now behind.
The new version start at 2.7.0

Update transcript variation pipeline - remove ehive version

---

modules/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm

The method to calculate the codon was updated in release 113 -[ check this PR](https://github.com/Ensembl/ensembl-variation/pull/1067/files).
After this update, the `Codons` and `Consequence` are wrong for some RefSeq transcripts.
Check ticket: https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6640
The line `substr($cds, $tv->cds_start(undef, $tr->strand * $shifting_offset) -1, $vf_nt_len) = $seq;` has been removed from the method but it is important for these RefSeq transcripts.
This code edits the `$cds` at the specific position start and end ($tv->cds_start(undef, $tr->strand * $shifting_offset) -1, $vf_nt_len). It replaces the allele by $seq. 
This code update should be cherry-picked to 113. 
It should fix the following issues:
https://github.com/Ensembl/ensembl-vep/issues/1775 …

Fix method codon() in TranscriptVariationAllele

---

cpanfile

`XML::Hash::XS` breaks the tests for perl 5.14
As this package is only used by the ClinVar import we can temporarily remove it from cpanfile. Later we'll find another package to import XML and/or remove 5.14 from the tests.

Remove XML::Hash::XS from cpanfile

---

scripts/import/clinvar_post_process.pl

In the February release there is a new term: `conflicting classifications of pathogenicity`

Add new term to ClinVar post_process script

---

modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/Constants.pm
modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportAnimalQTL.pm
modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportOMIA.pm

[ENSVAR-6663](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6663)
Add import for non reference species such as chicken red jungle fowl and cat abyssinian for OMIA and AnimalQTL
**AnimalQTL**: Add non reference species to the list and add their respective url for download
**OMIA**: Add non reference species to the list and copy the file for reference species as was done for sheep and dog before. Made the logic more generic by adding a hash `%nonref_species` to list all such species.
For sheep we have now changed according to the reference update. So, `ovis_aries` is now rambouillet and `ovis_aries_texel` is for texel.
It seemed we were setting `inputFile` as absolute where `animalqtl_inputDir` does not exist or the downloaded file not exist in that directory. But where the file exist we …

Phenotype pipeline: consider non reference species

---

scripts/misc/update_meta_coord.pl

Adding the option `--type` to argument. 
It dies because private_db does not have variation in the name.

Changes to the meta coord script for private db

---

modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/ReleaseDumps_conf.pm

The GVF dump step fails on memory but does not get retried higher memory jobs. It is because the job are SIGKILLed with return code 9 which is ambiguous to what actually happened. 
It is best to remove retry job steps altogether and run all jobs with high memory.

Run all GVF dump job as high mem

---

scripts/import/import_clinvar_xml

- Update the ClinVar script to save the ref allele as attrib_type `clinvar_ref_allele`.
- Fix bug in attrib variation_names. new variants have too many rsids, I updated the code to only include the supported length.
Ticket: [ENSVAR-5773](https://embl.atlassian.net/browse/ENSVAR-5773)

Update ClinVar script to save ref allele
