- modules/Bio/EnsEMBL/Variation/DBSQL/IndividualGenotypeFeatureAdaptor.pm
- scripts/import/import_vcf.pl
This change is needed for genotype phasing to be retrieved correctly.
> Added genotype phasing when creating objects from adaptor

- sql/patch_87_88_b.sql
- sql/table.sql
This will be consistent with changes in core and compara
> Update seq_region to varchar 255

- C_code/Makefile
- C_code/ld_vcf.c
Hello,
I have had a look at the LD code and found some pretty major time wasting. It would appear that an acceleration of ~10 can be achieved on a simple test, also reducing complexity from O(x^2) to O(x) when searching for the neighbourhood of a SNP. 
I tested it for regression on a simple test, but this could be tested further. 
Cheers,
Daniel
> Refactoring LD code

- scripts/import/import_vcf.pl
For VCF loader I want to add the option to add command line arguments for source I don't want to merge into
> command line option to add sources that we do not want to merge into

- modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/BaseDataDumpsProcess.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/CleanUp.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/Config.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/FileUtils.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/Finish.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/FinishDumpPopulation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/InitJoinDump.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/InitSubmitJob.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/InitValidation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/JoinDump.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/PopulationDumps_conf.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/PreRunChecks.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/README
- modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/ReleaseDumps_conf.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/Report.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/SpeciesFactory.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/SubmitJob.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/Validate.pm
Reverts Ensembl/ensembl-variation#57
> Revert "Registry and divisions support"

- modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/InitSubmitJob.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/ReleaseDumps_conf.pm
Minor changes to the GVF/VCF pipeline. One bug fix for EG divisions and minor clean up of the config file. I've tested these changes on Plants EG 37.
> Removed options from parent package

- sql/patch_90_91_a.sql
- sql/patch_90_91_b.sql
- sql/table.sql
Patch for schema version. Patch info still to be added to table.sql
> patch for schema 91

- modules/Bio/EnsEMBL/Variation/DBSQL/VariationAdaptor.pm
- modules/t/variationAdaptor.t
- scripts/import/import_variant_synonyms
Requires new API method to store synonyms for existing variant
> initial synonym importer - loads PharmGKB data

- modules/t/LDFeatureContainerAdaptor.t
Clean up old LDFeatureContainerAdaptor tests:
- we only need to test code that uses genotypes from VCF files
- test that LD values are computed correctly
- test all fetch methods
> update test cases. Check LD values.

- modules/t/test-genome-DBs/homo_sapiens/variation/table.sql
Update characterset to match e91 patch
> Update characterset for publication.authors

- sql/table.sql
Update of ancestral allele description.
Make allele minor_allele and minor_allele_count descriptions consistent
> Update column descriptions

- modules/Bio/EnsEMBL/Variation/Pipeline/TranscriptEffect.pm
Addresses issues encountered in JIRA ticket ENSVAR-790
> when not using FASTA, increase seq retrieval cache size

- modules/Bio/EnsEMBL/Variation/Pipeline/EquivalentAlleles/FindEquivalentAlleles.pm
Multi-allelic variants sometimes share multiple alleles with each other leading to duplicated 'equivalent variant' attributes.
> store equivalent variant only once

- sql/patch_91_92_a.sql
- sql/patch_91_92_b.sql
- sql/table.sql
Add patch to update to new release. Add patch for adding index to regulation related tables.
> Anja 92/patch regulation

- modules/t/LDFeatureContainerAdaptor.t
thanks @helensch for pointing out the mistake.
> import warning from Test::Warnings

- modules/Bio/EnsEMBL/Variation/DBSQL/PhenotypeFeatureAdaptor.pm
- modules/Bio/EnsEMBL/Variation/PhenotypeFeature.pm
- modules/t/phenotypeFeatureAdaptor.t
- modules/t/test-genome-DBs/homo_sapiens/variation/attrib_type.txt
- modules/t/test-genome-DBs/homo_sapiens/variation/table.sql
- scripts/import/import_clinvar_xml
- sql/attrib_entries.sql
- sql/patch_91_92_d.sql
- sql/table.sql
- script updated for bulk loading of 2 new phenotype_feature_atrribs
- new table created to store submitter descriptions as they are very long strings so would make phenotype_feature_atrrib large - submitter ids stored here instead
- packing/unpacking methods added to the adaptor
- convenience methods added to object
>  Store ClinVar submitters and last evaluated date 

- modules/Bio/EnsEMBL/Variation/Utils/VariationEffect.pm
- modules/t/variation_effect.t
Annotates inversions starting in the 5' region that affect start codons as 'start_lost'
> Annotates inversions starting in the 5' region that affect start codons as 'start_lost'

- modules/Bio/EnsEMBL/Variation/DBSQL/PublicationAdaptor.pm
- modules/Bio/EnsEMBL/Variation/Utils/Date.pm
- modules/t/date.t
- scripts/import/import_EPMC.pl
Updates to:
- store the date the pipeline is run in meta 
- improve comments and log file names
- don't check citations which are already loaded
- use https 
- only update display statuses which are wrong
- write out variants which were not found in the same format they were input
- add goat aliases
> Citation loader

- modules/Bio/EnsEMBL/Variation/DBSQL/PhenotypeFeatureAdaptor.pm
- modules/t/phenotypeFeatureAdaptor.t
- fetch_all_by_associated_gene , count_all_by_associated_gene : 
- added check for gene_name vs gene_object 
- added corresponding tests
- tidied up parameter documentation
> add check for gene_name vs gene_object and method documentation tidy up

- modules/t/publicationAdaptor.t
- modules/t/test-genome-DBs/homo_sapiens/core/biotype.txt
- modules/t/test-genome-DBs/homo_sapiens/core/meta.txt
- modules/t/test-genome-DBs/homo_sapiens/core/table.sql
- added new CORE table : biotype and corresponding test data
- fixed 1 declaration masking case
> add core biotype test data

- scripts/import/import_phenotype_data.pl
Rat Genome Database QTL phenotype import:
- import only VT description as phenotype description (same as e92)
- addition of the VT accession to phenotype_ontology_accession, mapped_by: RGD and mapping_type: is
- addition of QTL_RGD_ID as external_id phenotype_feature_attrib
- addition of CURATED_REF_PUBMED_ID as pubmed_id phenotype_feature_attrib
Additional modifications:
- code extended to check for existing ontology_mapping attrib for specific mapping source assignment if available
> RGD phenotype import expanded

- modules/Bio/EnsEMBL/Variation/AlleleFeature.pm
- modules/Bio/EnsEMBL/Variation/DBSQL/AlleleFeatureAdaptor.pm
- modules/Bio/EnsEMBL/Variation/DBSQL/StrainSliceAdaptor.pm
A few small changes and mostly formatting for better seeing what is going on. This fixes together with a [core PR](https://github.com/Ensembl/ensembl/pull/231) the alignments on the re-sequencing view.
> Update strain slice

- scripts/import/import_vcf.pl
- scripts/import/import_vcf_compress.pl
- scripts/misc/veplotyper.pl
Correct link to helpdesk in these scripts.
> Remove personal email

- modules/t/vep.t
Finally found the reason for the failed tests for 5.26
> select vf by allele_string

- modules/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm
This will fix a problem with the[ variation table view](https://plants.ensembl.org/Oryza_sativa/Gene/Variation_Gene/Table?db=core;g=Os05g0113900;r=5:738208-739079;t=Os05t0113900-0).
> test with defined

- scripts/import/import_human_ontology_terms.pl
- add specie option to allow the script to import VT ontologies from OLS exact and OLS partial for non-human species
> update the code to import VT for non-human species

- scripts/import/import_human_ontology_terms.pl
- update order of ontology accession mapping order: first use ols_exact, on the rest unmapped use ols_partial and on the remaining unmapped terms use zooma_exact
- update zooma_exact to use high mappings only
- corrected one of the ols_partial regex
> update human ontology accession mapping script

- modules/Bio/EnsEMBL/Variation/Pipeline/Remapping/FinishVariationFeatureQC.pm
- modules/Bio/EnsEMBL/Variation/Utils/RemappingUtils.pm
Fixing [some problems](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-1106) which have been noticed by Helen when remapping cat.
> Remapping updates prf93

- scripts/export/release/dump_gvf.pl
- scripts/misc/release/gvf2vcf.pl
https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-1045
> Eg dumps prf93

- modules/Bio/EnsEMBL/Variation/DBSQL/TranscriptVariationAdaptor.pm
- modules/t/transcriptVariationAdaptor.t
Attemped fix for https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-4496.
> add count by transcript for TranscriptVariation

- modules/Bio/EnsEMBL/Variation/PhenotypeFeature.pm
- modules/t/phenotypeFeature.t
- added pubmed id, MIM id & review status get methods
> phenotype feature convenience methods

- scripts/misc/update_meta_coord.pl
Script inspired by [core's version](https://github.com/Ensembl/ensembl/blob/release/92/misc-scripts/meta_coord/update_meta_coord.pl) for updating variation meta_coord tables in an automated way.
> script updates meta_coord table

- modules/Bio/EnsEMBL/Variation/Pipeline/Remapping/FinishVariationFeatureQC.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/Remapping/PreRunChecks.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/Remapping/RemappingVariationFeature_conf.pm
- modules/Bio/EnsEMBL/Variation/Utils/RemappingUtils.pm
Addressing a few issues from https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-1106
> Remapping updates

- modules/Bio/EnsEMBL/Variation/DBSQL/ProteinFunctionPredictionMatrixAdaptor.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/ProteinFunction/InitJobs.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/ProteinFunction/ProteinFunction_conf.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/ProteinFunction/RunDbNSFP.pm
- modules/Bio/EnsEMBL/Variation/ProteinFunctionPredictionMatrix.pm
- modules/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm
The PR contains pipeline for importing scores from dbNSFP file and new methods for retrieving scores from database. Remaining tasks are adding tests and minor pipeline updates. Those will be coming as post release fixes. Progress will be documented here: https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-1204
> Dbnsfp updates 94

- scripts/import/clinvar_post_process.pl
extra checks for variants inserted after ClinVar import
> add variant qc methods

- modules/Bio/EnsEMBL/Variation/Pipeline/VariantQC/FinishVariantQC.pm
- modules/Bio/EnsEMBL/Variation/Utils/QCUtils.pm
- scripts/import/dbSNP/ImportTask.pm
Changes from b151 import of dbSNP
> dbSNP import updates

- modules/Bio/EnsEMBL/Variation/Pipeline/ProteinFunction/BaseProteinFunction.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/ProteinFunction/InitJobs.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/ProteinFunction/ProteinFunction_conf.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/ProteinFunction/RunCADD.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/ProteinFunction/RunDbNSFP.pm
- modules/Bio/EnsEMBL/Variation/ProteinFunctionPredictionMatrix.pm
- modules/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm
- scripts/import/post_import_phenotypes.pl
Import CADD data from original CADD file and not dbNSFP file.
Update how we store CADD scores in protein function matrix.
Update MetaSVM to MetaLR because for the latter scores go from 0-1 which is easier to store in the matrix.
Some bug fixes.
> Post branc 94 protein function

- scripts/import/import_ancestral_alleles.pl
Add meta entry about most recent run.
Assign ancestral allele of size greater 1.
Some efficiency improvements: don't dump variations if run in complete load mode.
Some code formatting.
> Post 94 ancestral allele

- modules/Bio/EnsEMBL/Variation/DBSQL/LDFeatureContainerAdaptor.pm
- modules/Bio/EnsEMBL/Variation/VCFCollection.pm
- modules/t/LDFeatureContainerAdaptor.t
propagate https://github.com/Ensembl/ensembl-variation/pull/226 to release/94 and master
> Ld 94 strand fix

- sql/foreign_keys.sql
- sql/patch_94_95_a.sql
- sql/patch_94_95_b.sql
- sql/table.sql
Version patch and adds table to store allele synonyms
Replaces pull request #230
> Add schema and patch info for release 95

- modules/Bio/EnsEMBL/Variation/Pipeline/Remapping/BaseRemapping.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/Remapping/ComparePreviousAssembly.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/Remapping/FilterMapping.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/Remapping/FilterQTLMapping.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/Remapping/FilterStructuralVariationFeatureMapping.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/Remapping/InitStructuralVariationFeatureMapping.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/Remapping/LoadMapping.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/Remapping/ParseMapping.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/Remapping/PreRunChecks.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/Remapping/QtlQC.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/Remapping/RemappingQTL_conf.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/Remapping/RemappingStructuralVariationFeature_conf.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/Remapping/RemappingVariationFeature_conf.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/Remapping/StructuralVariationFeatureQC.pm
- modules/Bio/EnsEMBL/Variation/Utils/RemappingUtils.pm
-- I moved a lot of the filtering code which filters QTL and SVF mappings to the RemappingUtils module
-- I added QC code to run after remapping QTL and SVF
-- I started a comparison to previous assembly module
> Remapping updates 95

- modules/Bio/EnsEMBL/Variation/Pipeline/EquivalentAlleles/FinishEquivalentAlleles.pm
Reports for all attrib_id. In future need to limit this to co-located allele.
Reports if file open fails.
> Fix attrib count and open file check

- modules/Bio/EnsEMBL/Variation/Pipeline/RemappingVCF/InitRemapping.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/RemappingVCF/JoinRemapping.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/RemappingVCF/LoadFromVCF.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/RemappingVCF/Mapping.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/RemappingVCF/PreRunChecks.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/RemappingVCF/README
- modules/Bio/EnsEMBL/Variation/Pipeline/RemappingVCF/Remapping.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/RemappingVCF/RemappingVCF_conf.pm
Pipeline for remapping VCF files against a remapped variation database. The pipeline was tested for cow and horse.
> remapping code for VCF files

- modules/Bio/EnsEMBL/Variation/Pipeline/InitRegulationEffect.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/RegulationEffect.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/RegulationEffect_conf.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/SliceFactory.pm
Improve regulation pipeline by using split slice and calculate overlap between variant and regulatory or motif feature from split slice. Add option for using experimentally validated motif feature only (only works for human).
> Regulation updates 95

- modules/Bio/EnsEMBL/Variation/Pipeline/TranscriptEffect.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/VariationConsequence_conf.pm
Just some minor updates which helped to keep the transcript variation pipeline running even for very long running jobs.
> Tv updates 95

- modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/FinishDumpPopulation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/PopulationDumps_conf.pm
small updates to population data dumping pipeline
> Population dumps 95

- modules/Bio/EnsEMBL/Variation/Pipeline/DumpHGVS/DumpHGVS_conf.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/DumpHGVS/DumpRegionHGVS.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/DumpHGVS/FinishDumpHGVS.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/DumpHGVS/InitDumpHGVS.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/GetCAR/FinishGetCAR.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/GetCAR/GetCARSeqname.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/GetCAR/GetCAR_conf.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/GetCAR/InitGetCAR.pm
- scripts/import/load_car.pl
- scripts/import/process_car_lu.pl
Pipelines and scripts to add ClinGen Allele Registry Id (CAid) to allele_synonym
> Adding ClinGen Allele Registry Id to allele_synonym

- modules/Bio/EnsEMBL/Variation/Pipeline/DBSNPImport/DBSNPImport_conf.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/DBSNPImport/InitDBSNPImport.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/DBSNPImport/LoadDBSNPFile.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/DBSNPImport/ReportDBSNPImport.pm
- scripts/import/dbSNP_v2/dbsnp_v2_import_table.sql
- scripts/import/dbSNP_v2/init_load_dbsnp.pl
- scripts/import/dbSNP_v2/load_dbsnp.pl
Scripts and pipeline to import dbSNP-v2 JSON files.
JIRA ticket  for updates and documentation: ENSVAR-1512
> dbSNP-v2 import

- .travis.yml
This pull request should not be merged until branch 96 exists on the repositories
> Update travis for release/96

- scripts/import/clinvar_post_process.pl
- scripts/import/import_clinvar_xml
updates to: clinvar_post_process.pl and import_clinvar_xml
> add phenotype feature attribs counts to checks

- .travis.yml
- travisci/harness.sh
Same as #306 but without the read/write access change
> Fix path to BioPerl in the travis PERL5LIB

- scripts/misc/sources2html.pl
- scripts/misc/species_list.pl
Related to the PR https://github.com/Ensembl/public-plugins/pull/184
> Update scripts generating the Variation web doc

- modules/Bio/EnsEMBL/Variation/GERPAnnotation.pm
The new BigWig files are not in place yet but config files are already pointing to the new files and causing an error message on staging. This PR will fix the variant summary page.
> deal with undefined BigWig parser

- modules/Bio/EnsEMBL/Variation/Utils/Sequence.pm
- modules/t/sequence_utils.t
- scripts/import/clinvar_post_process.pl
- scripts/import/import_clinvar_xml
import clinvar script fix for issue ENSVAR-1637:
- fix QC allele check id 14
- update log messaging
- add special character checking
- add hgvs parsing for _delIns_ of format  7:g.5978687_5978689delinsC and _del_ of format 9:g.137233961_137234061del
Sequence.pm:
- add coverage for 2 more hgvs parsing cases 
- add tests for all hgvs parsed cases
> fix a few cases in import

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
Adding all conservation score files for our variation species for release/96
> add conservation files

- modules/Bio/EnsEMBL/Variation/Utils/FastaSequence.pm
Updated code to allow a flag to preserve any softmasking in the fasta file when fetching sequence. This is to avoid querying the repeat_feature table via the API as asking for masked sequence incurs a join between repeat_feature and repeat_consensus that becomes expensive when there are many jobs running in parallel. The flag is passed through into the overriden ->seq into the _raw_seq subroutine. The code in _raw_seq has been slightly refactored to to the uc call after fetching the sequence, unless the preserve_masking flag has been passed. Example usage would be: my  = ->(undef,undef,undef,1)
> Change to FastaSequence.pm to allow fetching softmasked sequence from file

- modules/Bio/EnsEMBL/Variation/DBSQL/MotifFeatureVariationAdaptor.pm
- modules/Bio/EnsEMBL/Variation/MotifFeatureVariation.pm
- modules/Bio/EnsEMBL/Variation/MotifFeatureVariationAllele.pm
Just quickly replacing deprecated code.
> replace deprecated code

- modules/t/test-genome-DBs/homo_sapiens/variation/attrib.txt
- modules/t/test-genome-DBs/homo_sapiens/variation/attrib_type.txt
- modules/t/test-genome-DBs/homo_sapiens/variation/protein_function_predictions.txt
- modules/t/test-genome-DBs/homo_sapiens/variation/table.sql
- modules/t/transcriptVariationAdaptor.t
Finally adding tests for newish methods.
> add test data and test new methods in TranscriptVariationAllele module

- modules/Bio/EnsEMBL/Variation/CADDAnnotation.pm
- modules/Bio/EnsEMBL/Variation/VCFCollection.pm
Same as https://github.com/Ensembl/ensembl-variation/pull/363 but now for master and release/97
> catch error

- scripts/import/post_import_phenotypes.pl
Should hopefully fix https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-2060
> reset display and consider variants with citations in final update

- scripts/export/dump_phenotypes.pl
updates based on latest code: https://github.com/Ensembl/VEP_plugins/pull/181
> correct extension bed to gvf

- modules/Bio/EnsEMBL/Variation/Pipeline/EquivalentAlleles/EquivalentAlleles_conf.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/EquivalentAlleles/FindEquivalentAlleles.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/EquivalentAlleles/FinishEquivalentAlleles.pm
Failed variations are now included.
Duplicates are reported - caused by resetting failed jobs
In future review if a unique index on variation_attrib is needed
> Updates to Equivalent Allele Pipeline

- modules/Bio/EnsEMBL/Variation/Pipeline/DumpVariationGeneName.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/FinishTranscriptEffect.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/LoadWebIndexFiles.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/VariationConsequencePreTasks.pm
- process genes with large number of transcripts by trancript
- remove variation_genename update
- put LOG_ files in separate directory and remove in PreTasks
Suggestions for future
- parametrize the values to decide to flow to transcript_factory
> Updates to transcript variation pipeline

- scripts/remap_gnomad/README
- scripts/remap_gnomad/append_to_crossmap_results.pl
- scripts/remap_gnomad/bgzip_mapping_results.sh
- scripts/remap_gnomad/cross_map.sh
- scripts/remap_gnomad/filter_mapping_results.pl
- scripts/remap_gnomad/final_variant_count_genomes.sh
- scripts/remap_gnomad/load_unmapped_variation.pl
- scripts/remap_gnomad/rename_trimmed_files.sh
- scripts/remap_gnomad/run_bgzip_mapping_results.sh
- scripts/remap_gnomad/run_cross_map.sh
- scripts/remap_gnomad/run_final_append_job_array.sh
- scripts/remap_gnomad/run_trim_gnomad_files.sh
- scripts/remap_gnomad/run_unique_mapping_results_to_VCF.sh
- scripts/remap_gnomad/tabix.sh
- scripts/remap_gnomad/trim_gnomad_files.sh
- scripts/remap_gnomad/unique_mapping_results_to_VCF.pl
- scripts/remap_gnomad/wget_gnomad_files.sh
- scripts/remap_gnomad/write_unmapped_variants.pl
move the files from ensembl-internal-variation/scripts to make sharing them easier. The files will be removed from ensembl-internal-variation/scripts
> move files from ensembl-internal-variation/scripts

- modules/Bio/EnsEMBL/Variation/DBSQL/BaseAnnotationAdaptor.pm
Same as https://github.com/Ensembl/ensembl-variation/pull/426
> recognize http too

- modules/Bio/EnsEMBL/Variation/Utils/VariationEffect.pm
Fix for ENSVAR-2318. For release98 and postreleasefix/98  only.
See PR #417 for master branch
> Revert PR#401 - remove start/stop_retained from COSMIC

- modules/Bio/EnsEMBL/Variation/AlleleFeature.pm
- modules/Bio/EnsEMBL/Variation/Phenotype.pm
- modules/Bio/EnsEMBL/Variation/Population.pm
- modules/Bio/EnsEMBL/Variation/Publication.pm
- modules/Bio/EnsEMBL/Variation/StrainSlice.pm
- modules/Bio/EnsEMBL/Variation/TranscriptVariation.pm
- modules/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm
- modules/Bio/EnsEMBL/Variation/Utils/Sequence.pm
- modules/Bio/EnsEMBL/Variation/Variation.pm
- modules/Bio/EnsEMBL/Variation/VariationFeature.pm
For podchecker fixes are for ENSVAR-1986, ENSVAR-902
> Fix documentation for examples and podchecker errors and warnings

- modules/Bio/EnsEMBL/Variation/Utils/Sequence.pm
- modules/Bio/EnsEMBL/Variation/VariationFeature.pm
- modules/t/sequence_utils.t
- modules/t/variationFeature.t
Used to create VCF line on web site
> update VF VCF writer to remove common trailing bases from SPDI

- scripts/import/dbSNP_v2/init_load_dbsnp.pl
- scripts/import/dbSNP_v2/load_dbsnp.pl
This PR replaces #444 
Used for load of dbSNP b153
> dbSNP import fixes for b153

- tools/linkage_disequilibrium/ld_tool
ld_tool species option failing as species being treated as flag. From example
./ld_tool --show_populations --species human
> Fix species option to be string

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
GERP file versions have been updated correctly. But somehow not the release version.
> update release version

- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/BasePhenotypeAnnotation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/CheckPhenotypeAnnotation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportAnimalQTL.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportCGC.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportGWAS.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportOrphanet.pm
- the first 3 commits are already merged part of PR https://github.com/Ensembl/ensembl-variation/pull/464
- fix for CGC json updates
- fix path for orphanet
> phenotype import needed updates -e99

- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/BasePhenotypeAnnotation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/CheckPhenotypeAnnotation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportCGC.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportOrphanet.pm
- modules/Bio/EnsEMBL/Variation/Utils/SpecialChar.pm
- first 3 commits are from PR https://github.com/Ensembl/ensembl-variation/pull/465
- use special char from utils
> updates to phenotype hive -e 100

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
The config update is needed for API users. I will have a separate PR for public-plugins.
> add salmon PRJEB34225 from EVA

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
Thanks @helensch for spotting the missing chromosomes
> add missing chr for salmon

- scripts/import/import_cosmic.pl
- adapt code for latest format
- inversion start=end+1
- add variation sets
> cosmic import updates - e100

- scripts/import/import_hgmd.pl
> update to HGMD import -e100

- scripts/import/import_hgmd.pl
- scripts/import/map_hgmd_coord.pl
- add evidence and display info at import
- insert default phenotype with 'non_specified' attrib (patch 99_100c)
> Updated to hgmd import -e100

- modules/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm
- modules/t/hgvs_parser.t
HGVS not supported: 
NC_000023.11:g.(?_126549383)(129592556?)del 
NC_000023.9:g.9688757-?_9693917+?del 
NC_000001.11:g.(155160963_155162030)insC 
JIRA ENSVAR-2535
> Add specific error message for unsupported HGVS

- modules/Bio/EnsEMBL/Variation/BaseVariationFeatureOverlapAllele.pm
Fix for https://github.com/Ensembl/ensembl-vep/issues/627. Transcript_ablation sometimes annotated as 'stop_lost,coding_sequence_variant,5_prime_UTR_variant,3_prime_UTR_variant,intron_variant'.
> fix transcript ablation -e98

- modules/Bio/EnsEMBL/Variation/BaseVariationFeatureOverlapAllele.pm
same as https://github.com/Ensembl/ensembl-variation/pull/486
> fix transcript ablation -e99

- scripts/import/import_all_sv_data.pl
More examples of phenotypes with weird characters that have to be replaced (ENSVAR-2713)
> SV import - replace weird characters 

- scripts/import/import_clinvar_xml
> Updates to  Clinvar import - e100

- scripts/import/import_cosmic.pl
- add evidence and display info at import
- insert default phenotype with 'tumour' attrib (patch 99_100c)
> Updated to cosmic import -e100

- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/BasePhenotypeAnnotation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/CheckPhenotypeAnnotation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/Constants.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/FinishPhenotypeAnnotation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/FinishPhenotypeAnnotationPipeline.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportAnimalQTL.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportAnimalSet.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportCGC.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportDDG2P.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportEGA.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportGWAS.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportHuman.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportIMPC.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportMGI.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportMIMmorbid.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportMouse.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportOMIA.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportOrphanet.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportRGD.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportZFIN.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/InitPhenotypeAnnotation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/MouseBasePhenotypeAnnotation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/OntologyMapping.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/PhenotypeAnnotation_conf.pm
- modules/Bio/EnsEMBL/Variation/Utils/SpecialChar.pm
- gwas import: update variation sets at import + update display flag at import + evidence attribs 
- checks: fix & update regex
- check if seq_regions exist, otherwise insert them
- refactor hive structure and flow
- do not remove phenotypes when cleaning the existing phenotype features
- add data types to sources
- bug fixes
> Updates phenotype hive import -e100

- modules/Bio/EnsEMBL/Variation/DBSQL/PhenotypeFeatureAdaptor.pm
Ignore phenotype is_significant flag, Jira: ENSVAR-2732
> temp fix for pheno - e99

- modules/Bio/EnsEMBL/Variation/ProteinHaplotype.pm
Bug fix for https://github.com/Ensembl/ensembl-vep/issues/671
> escape the special regex character

- modules/Bio/EnsEMBL/Variation/Utils/VariationEffect.pm
- modules/Bio/EnsEMBL/Variation/VariationFeature.pm
> Prevent repeated calculation of flanking sequence length

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
See https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5543
> update FTP URL ahead of data centre migration

- scripts/import/post_process_databases_tables.pl
Fix hash that contains all the citation attributes.
> Fix script to post process db tables

- scripts/import/import_vcf.pl
> Remove flanking seq table

- sql/patch_100_101_b.sql
- sql/table.sql
Add 3 attributes to variation_citation.data_source_attrib: 
620: ClinVar
619: dbGaP
618: GWAS
> Add attrib ids to variation_citation

- modules/Bio/EnsEMBL/Variation/Pipeline/ProteinFunction/RunSift.pm
https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-2381
> add file and dir check

- scripts/import/import_all_sv_data.pl
Some cosmic variants had somatic = 0 after cosmic import. 
Ticket: ENSVAR-2980
> Fix somatic flag for SV cosmic import

- modules/Bio/EnsEMBL/Variation/DBSQL/VariationAdaptor.pm
- modules/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm
- modules/Bio/EnsEMBL/Variation/Utils/Sequence.pm
- scripts/import/import_clinvar_xml
- add evidence attribs to variation and variation feature
- add variation set ids to variation feature 
- add phenotype evidence const to Sequence utils
- update VariationAdaptor update method to avoid undef errors   
- created jira ticket for VariationFeatureAdaptor to include variation sets in the future ENSVAR-2717
> import clinvar updates for - e101

- modules/Bio/EnsEMBL/Variation/Pipeline/VariationConsequence_conf.pm
And set max_distance to 0 at the same time
> Prevent running of var class updates for human

- modules/Bio/EnsEMBL/Variation/DBSQL/BaseAnnotationAdaptor.pm
We are likely to switch Ensembl to retrieving files from ftp server using http protocol rather than ftp. Here is the code to support this change — it checks the protocol of the link to the file, and uses an http client rather than an ftp client if the link uses http protocol.
Related PR in public plugins: https://github.com/Ensembl/public-plugins/pull/320
Related Jira ticket: https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5607
> Switch between http and ftp when checking for presence of remote files

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
URL can already by reverted for 100 https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5543
> revert after datacentre move

- scripts/import/project_feature.pl
- add reconnect_when_lost
- move init columns into own method
PR for jira ENSVAR-3172.
> update projection script

- scripts/import/import_all_sv_data.pl
Study table has some values 'NULL' instead of NULL
ENSVAR-3134
- Changed the SQL queries to insert or update a study
- Found HTML character in study description `&lt;` add to `replace_text`
> Import SV - change sql to insert or update study 

- scripts/import/post_process_databases_tables.pl
add done print statement to publications section
> update post process script

- scripts/import/import_all_sv_data.pl
individual table with 'NULL' (ENSVAR-3110)
phenotype table (ENSVAR-2960)
Fix mouse individual gender
> SV import fix NULLs

- sql/attrib_entries.sql
ENSVAR-2550
Following PR: #567
> Add attribute

- sql/attrib_entries.sql
- sql/patch_101_102_a.sql
- sql/patch_101_102_b.sql
- sql/table.sql
- patch a: schema update 102
- patch b: new clinsig attribute
> Schema update for e102

- scripts/import/clinvar_post_process.pl
- fix import script for bug  ENSVAR-3206 (fixed via sql in e101)
- add warning for sanity check of rsID  , ENSVAR-3177
> fixes for clinvar import -e102

- scripts/import/import_cosmic.pl
> cosmic fix insertion

- modules/Bio/EnsEMBL/Variation/DBSQL/PhenotypeAdaptor.pm
- modules/t/phenotypeAdaptor.t
same as https://github.com/Ensembl/ensembl-variation/pull/614
> PhenotypeAdaptor store for new Phenotypes - e101

- modules/Bio/EnsEMBL/Variation/Utils/SpecialChar.pm
- modules/t/specialChar.t
- scripts/import/import_all_sv_data.pl
Move method decode_text from SV import to Utils so it can be used by other imports and pipelines.
> Move decode_text to Utils

- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/CheckPhenotypeAnnotation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportCGC.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportOrphanet.pm
> Updates to phenotype hive -e102

- scripts/import/import_decipher.pl
- scripts/import/import_decipher_snv.pl
insert phenotype class attrib id for private db
> update import script for privatedb - master

- modules/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm
- modules/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm
- modules/t/variationFeatureAdaptor.t
ENSVAR-2729
HGVS can't handle multi-exon alterations. Example: ENST00000321030:c.1_238del (deletion of exon 2 and 3).
> HGVSc handle multi-exon alterations

- modules/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm
- modules/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm
- modules/t/variationFeatureAdaptor.t
> HGVSc handle multi-exon alterations 101

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
gerp files haven't changed for 102. I only updated the name of the release folder. I also added the gerp file for sheep rambouillet.
> update gerp file location for 102

- modules/Bio/EnsEMBL/Variation/Utils/SpecialChar.pm
- scripts/import/import_clinvar_xml
- address special characters
- clean log exit messages
> Update clinvar import - e103

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
Web approved copy of new CADD file to FTP site for release/102.
> update cadd file

- .travis.yml
- README.md
Version updates only to be done on release branch.
> Release branch updates 103

- scripts/import/import_all_sv_data.pl
Add source data_types (ENSVAR-3412)
Fix phenotypes with a comma in the description to avoid being split into two different phenotypes.
> SV import updates

- scripts/import/import_EPMC.pl
Update the URL to check the publication species. 
ENSVAR-3558
> Fix citations import

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
> move ggvp data to ensembl ftp

- modules/Bio/EnsEMBL/Variation/DBSQL/PhenotypeAdaptor.pm
- modules/Bio/EnsEMBL/Variation/Phenotype.pm
- modules/t/phenotype.t
- modules/t/phenotypeAdaptor.t
- modules/t/test-genome-DBs/homo_sapiens/variation/phenotype.txt
ParaSite use this column in the phenotype table and getters are required.
> Add API support for phenotype.stable_id - for e103

- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/BasePhenotypeAnnotation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/CheckPhenotypeAnnotation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/Constants.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/FinishPhenotypeAnnotation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportAnimalQTL.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportAnimalSet.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportCGC.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportDDG2P.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportEGA.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportGWAS.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportHuman.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportIMPC.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportMGI.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportMIMmorbid.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportMouse.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportOMIA.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportOrphanet.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportRGD.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportZFIN.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/InitPhenotypeAnnotation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/OntologyMapping.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/PhenotypeAnnotation_conf.pm
- modules/Bio/EnsEMBL/Variation/Utils/SeqRegionUtils.pm
fixes:
- gwas NR
- add seq_region_ids update for human
- AnimalQTL: import date only updated for imported species, species requiring remapping are skipped
- update meta_coord phenotype_feature related entries
address previous PR comments/other fixes:
- use hash for branch job flows
- define Human_var , Human_gene run_types
- move run_type from global to internal param 
- make finish module standalone
jira tickets: ENSVAR-3223, ENSVAR-3455, ENSVAR-3373, ENSVAR-2724, ENSVAR-2871, ENSVAR-3140
> Update phenotype import hive - e103

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
We remapped MGP data with CrossMap for release/103.
> add mgp GRCm39 files

- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportAnimalQTL.pm
> Fix needed for pig AnimalQTL data

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
For 
- feature description: ENSVAR-3413
- GRCh38 sandbox testing: ENSVAR-3702
- GRCh37 API testing: ENSVAR-3699
- GRCh38 API testing: ENSVAR-3705
> Add configuration for GEM-J frequency

- modules/Bio/EnsEMBL/Variation/Pipeline/SpliceAI/BaseSpliceAI.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/SpliceAI/FinishFiles.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/SpliceAI/MergeFiles.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/SpliceAI/SpliceAI_conf.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/SpliceAI/SplitFiles.pm
A few updates to the pipeline:
- fix the vcf files headers
- change the way the final files were merged (not working before) 
- set_chr_from_filename not working in SplitFiles 
ENSVAR-3684
> Update SpliceAI pipeline

- modules/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm
> Revert fix coord system

- modules/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm
Revert PR #667 
This PR fixes failing test in ensembl-vep Parser_HGVS.t`
> Revert fix coord system 

- scripts/import/import_clinvar_xml
- add lookup by canonical spdi
- check all alleles for snps
- print change to warn
> Update ClinVar import - master / e104

- scripts/misc/generate_population_table.pl
PR to be made for e104 on approval
> Add url for GEM-J

- modules/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm
- modules/t/variationFeatureAdaptor.t
Same as #686 
Ticket: ENSVAR-3947
> SPDI uses the sequence version number

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
> Add new EVA species nile tilapia

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
Adding VCF config for VCF from EVA for american mink.
For ENSVAR-3909
> Add EVA species american mink

- scripts/import/import_clinvar_xml
- update error, print logs ENSVAR-3893
- revert version date to filename ENSVAR-3726
- catch e104 encountered RCV sql error ENSVAR-3897
> Update ClinVar import -e104

- scripts/import/import_all_sv_data.pl
1. skip non-reported phenotypes (ENSVAR-3995) 
2. add class_attrib_id to phenotypes and report which clinical significance is not supported (ENSVAR-3581)
3. after import check if there are any phenotype entries without phenotype feature
> Update SV import - improve phenotypes and add post-processing checks

- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/BasePhenotypeAnnotation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/CheckPhenotypeAnnotation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/FinishPhenotypeAnnotation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportAnimalQTL.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportCGC.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportDDG2P.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportEGA.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportGWAS.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportMGI.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportMIMmorbid.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportMouse.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportOMIA.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportOrphanet.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportRGD.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportZFIN.pm
- review all make_path use: ENSVAR-3961
- refactor fetch/save counts to internal production db: ENSVAR-3917
requires https://github.com/Ensembl/ensembl-internal-variation/pull/52 
- e105: AnimalQTL update to use only reported data, no remapped files expected
> Update phenotype hive import - e105/master

- modules/Bio/EnsEMBL/Variation/Variation.pm
- modules/t/variation.t
Reverts Ensembl/ensembl-variation#699
> Revert "VariationFeature - get variant synonyms "

- scripts/misc/generate_vep_examples.pl
Add option to VEP example script, to write directly to a core database. This means that the ini files do not need to be updated (although this script still always produces the files, because not doing so would involve a significant rewrite).
This relates to ticket https://www.ebi.ac.uk/panda/jira/browse/ENSPROD-6774. Historically, VEP examples for non-verts have been handled by the EG team, then Web, and now Production - it landed with us because we have a pipeline to add gene-related examples, so it makes sense to do VEP examples within the same pipeline. (These non-vert examples have always been stored in the core db meta table, since updating ini files does not easily scale to hundreds of species.)
We run the example pipeline every release, for new/updated vert and non-vert species; …
> Write VEP examples directly to a core database

- modules/Bio/EnsEMBL/Variation/Variation.pm
- modules/t/variation.t
Same as #699. 
This PR fixes the test failing in perl 5.26
> Report variant synonyms

- scripts/import/import_clinvar_xml
> ClinVar import - fetch more pubmed IDs

- modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/ReleaseDumps_conf.pm
Updates required to work on codon cluster. I created default values for hive_root_dir and ensembl_cvs_root_dir. Look up so.obo file from sequence ontology git repo.
> codon updates

- scripts/import/import_variant_synonyms
UniProt file (https://www.uniprot.org/docs/humsavar) has different terms for variant classification. 
ENSVAR-4191
> Update variant synonyms import with new terms

- modules/Bio/EnsEMBL/Variation/Utils/SpecialChar.pm
These are special charaters found in publications.
> Add special charaters to replace_hex()

- scripts/import/import_vcf.pl
For pribate db grch38: update script to use HGVS grch38. 
More info: ENSVAR-4289
> Update Mastermind import (private db)

- scripts/import/import_EPMC.pl
Use new EPMC input file:
- update `parse_EPMC_file` to parse new file structure (update the spacing)
- more info: ENSVAR-4297
Improve UCSC publications:
- check if ucsc id which is going to be inserted into `publication.ucsc_id` is a PMCID. If yes, then insert value into `publication.pmcid`
- more info: ENSVAR-4192
> Update citation import

- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/CheckPhenotypeAnnotation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/Constants.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportOMIA.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportRGD.pm
Fix rat assembly: ENSVAR-4298
Add canis_lupus_familiarisboxer to pipeline
> Fix phenotype import for rat and add boxer

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
> Update config for NCBI ALFA release 2

- scripts/misc/create_MTMP_tables.pl
Script didn't work on codon with just `DBI->connect...`. Replacing it with Bio::EnsEMBL::DBSQL::DBConnection is working.
> change to using DBConnection

- scripts/import/import_EPMC.pl
publication.title max size is 300 varchar. 
Update script to truncate title if length >300
ENSVAR-4314
> Update citation import - truncate title

- scripts/import/import_clinvar_xml
> Update ClinVar import - remove allele_synonym entries

- scripts/misc/generate_vep_examples.pl
Fix for release/105
When approved PR will be made for postreleasefix/106
> VEP examples generation - check slice exists

- C_code/ld_vcf.c
> Fix ld_vcf to for multiple files and region

- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportWORMBASE.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/PhenotypeAnnotation_conf.pm
> Fix Phenotype pipeline - wormbase warning

- .travis.yml
Tested new clone command and works sucessfully.
> Updating funcgen branch from master to main for travis.yml

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
> Update gnomAD version v3.1.2

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
> Remove salmon config - variants not remapped new assembly

- modules/Bio/EnsEMBL/Variation/Pipeline/TranscriptEffect.pm
Only store MANE transcripts in BioMart 
ENSVAR-4568
> Update transcript effect pipeline 

- scripts/import/import_cosmic.pl
> Update COSMIC import

- scripts/import/import_EPMC.pl
> Update citations import (e107)

- modules/Bio/EnsEMBL/Variation/Pipeline/DBSNPImport/DBSNPImport_conf.pm
- scripts/import/dbSNP_v2/init_load_dbsnp.pl
- scripts/import/dbSNP_v2/load_dbsnp.pl
> Updates to dbSNP for new cluster

- .travis.yml
[ENSVAR-4782](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4782)
> Corrected branch for funcgen and hive in travis config file

- scripts/import/clinvar_post_process.pl
- scripts/import/import_clinvar_xml
- Update version (ENSVAR-4439)
- Fix sql query to remove entries from allele_synonym and also remove entries from variation_citation (ENSVAR-4442)
- Update post process clinvar script (ENSVAR-4555)
> Update ClinVar import (e107)

- modules/Bio/EnsEMBL/Variation/Pipeline/ProteinFunction/InitJobs.pm
Fetch only refseq transcripts
Details: ENSVAR-4481
> Fix protein function pipeline for mouse - fetch refseq

- modules/Bio/EnsEMBL/Variation/Pipeline/TranscriptEffect.pm
For human: only write MANE transcripts to MTMP_transcript_variation
For other species: write all transcripts
ENSVAR-4767
> Update transcript variation pipeline

- scripts/misc/generate_population_table.pl
- scripts/misc/update_web_documentation.pl
Added 2 fixes - 
- Script should be able to run from anywhere
- Check for output dir first and fail if does not exist. (one of my run lasted 16hrs and html files did not generated as output dir was not present)
> Some update on public doc creation script

- modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/InitJoinDump.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/JoinDump.pm
For example chicken with previous assembly have name - 
`gallus_gallus_gca000002315v5`
> Fix for species with gca in their name

- scripts/import/import_vcf.pl
[ENSVAR-4931](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4931)
> Import vcf changes

- scripts/misc/species_list.pl
Currently we have species database which name can contain numbers such as - 
**Gallus_gallus_gca000002315v5**
Updated regex to handle that. Also in the species name we do not want the `gca` to appear.
> Fix species list doc creation script

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
Dog and Dog boxer had same id which cause problem with the API.
> Update to make unique ids among dog breeds

- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportDDG2P.pm
[ENSVAR-4516](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4516)
> Supporting multiple panels g2 p

- scripts/import/clinvar_post_process.pl
- scripts/import/import_clinvar_xml
> Update ClinVar import script to populate transcript_variation

- scripts/import/import_variant_synonyms
Add UniProt synonyms to variation_set_variation: [ENSVAR-3720](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-3720)
Support EVA synonyms: [ENSVAR-4968](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4968)
Support Pig chip Consortium: [ENSVAR-4969](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4969)
> Update variation synonyms script

- scripts/import/import_set_from_file.pl
> add set loader

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
JIRA - [ENSVAR-4967](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4967)
> Support crab_macaque

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
Add support for remote EVA variants from Prairie vole (_Microtus ochrogaster_).
Check first https://github.com/Ensembl/public-plugins/pull/569
> Add prairie vole EVA configuration

- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/BasePhenotypeAnnotation.pm
Replace unicode hex in phenotype description.
> Update phenotype pipeline

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
> Add macaca mulatta VCF config (EVA variants)

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
We want to add CADD information to web variant table information.
1) Check in sandbox that alterations work for pig `
Change tolerance - CADD` . I.e,
http://wp-np2-11.ebi.ac.uk:7080/Sus_scrofa/Variation/Explore?db=core;r=2:5904477-5950182;v=rs707529833;vdb=variation;vf=44527978
> feat: add sus_scrofa to web part

- modules/Bio/EnsEMBL/Variation/Pipeline/ProteinFunction/ProteinFunction_conf.pm
- modules/Bio/EnsEMBL/Variation/Utils/BaseProteinFunctionAnnotation.pm
- modules/Bio/EnsEMBL/Variation/Utils/DbNSFPProteinFunctionAnnotation.pm
Update protein function pipeline to support dbSNFP 4.3a and the SIFT version 6.2.1 on codon.
> Protein function pipeline - update dbNSFP version 4.3a and SIFT 6.2.1

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
[ENSVAR-5001](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5001)
> Update GERP scores paths to 108

- modules/Bio/EnsEMBL/Variation/Pipeline/GetCAR/GetCARSeqname.pm
As per Jira ticket - ENSVAR-4991.
Tested command and generates output files correctly.
> Removing variants that break CAR API

- scripts/import/import_clinvar_xml
This PR is just to update the ClinVar script, COSMIC will be updated later.
Details in: ENSVAR-5014
> Fix ClinVar import

- modules/Bio/EnsEMBL/Variation/BaseAnnotation.pm
- modules/Bio/EnsEMBL/Variation/DBSQL/VCFCollectionAdaptor.pm
- modules/Bio/EnsEMBL/Variation/VCFCollection.pm
- modules/t/VCFCollection.t
- modules/t/vcf_config.json
> cherry-pick #830 from postreleasefix/108 branch

- scripts/export/dump_phenotypes.pl
Dumping phenotypes quick bug fix
> Dump phenotypes - fixing the bug

- scripts/import/dbSNP_v2/init_load_dbsnp.pl
JIRA: [Card](https://github.com/Ensembl/ensembl-variation/pull/863)
This should also include coord_system_ids and coord_system table to `init_load_dbsnp.pl`
1) Test creation init_load_dbsnp.pl and check if seq_region table coord_system was also populated. More information on JIRA card.
> feat: Add coord_system to init_load_dbsnp

- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/BasePhenotypeAnnotation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/CheckPhenotypeAnnotation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportCGC.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/PhenotypeAnnotation_conf.pm
- scripts/python/download_cgc_file.py
Update import for source CGC:
- the URL to download the input is different
- input format is different
- save more data into phenotype_feature_attrib: [ENSVAR-3591](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-3591) this change requires we add 3 more attrib types into the attrib_type table.
> Update phenotype pipeline CGC import

- scripts/misc/species_list_detailed_counts.pl
link - http://wp-np2-11.ebi.ac.uk:7070/info/genome/variation/species/species_detailed_counts.html 
We were showing SV count from only DGVa source. Now we have added dbVar too.
> Update SV count in the doc

- modules/Bio/EnsEMBL/Variation/LDFeatureContainer.pm
- modules/Bio/EnsEMBL/Variation/Utils/VEP.pm
- modules/t/VCFVariation.t
- modules/t/transcriptHaplotypeCollection.t
- scripts/import/import_phenotype_data.pl
- scripts/misc/veplotyper.pl
Remove comments
Remove `$DB::single = 1`
[ENSVAR-2534](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-2534)
> Cleanup code

- tools/variant_simulator/README.md
- tools/variant_simulator/simulate_variation
Update the script to generate SpliceAI files (-spliceai)
Add option to generate variants only overlapping MANE transcripts (-onlyMane)
> Update simulate_variation script to generate SpliceAI files

- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportGWAS.pm
[ENSVAR-4566](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4566)
> Changes to the GWAS_odds_ratio

- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/BasePhenotypeAnnotation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/FinishPhenotypeAnnotation.pm
[ENSVAR-5198](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5198)
To test, commenting out - line 120 - 126 in CheckPhenotypeAnnotation is suggested.
> Cleaning unused phenotype entries after each run

- scripts/import/import_vcf.pl
This PR only fixes the indentation of the script import_vcf.pl
> Fix indentation import_vcf

- scripts/import/import_EPMC.pl
- sql/attrib_entries.sql
Add new attrib for release 110
[ENSVAR-4990](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4990)
> Add attrib for DDG2P citations

- modules/Bio/EnsEMBL/Variation/VCFCollection.pm
- modules/t/VCFCollection.t
Refactor code to be easier to add more annotations in the future.
> Refactor VCFCollection code

- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/BasePhenotypeAnnotation.pm
Add another check to find phenotype descriptions that are already stored in the database.
Details: [ENSVAR-2545](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-2545)
> Update phenotype pipeline - check phenotype description

- nextflow/ProteinFunction/README.md
- nextflow/ProteinFunction/main.nf
* Consistent example across README.md and `--help`
* Add mandatory database arguments to example
> SIFT/PolyPhen-2 Nextflow pipeline: improve command example

- scripts/import/import_vcf.pl
- Add a command to update the source version
- Skip synonyms insertion if there are multiple rs ids
- Add evidence attribs to variation and variation feature when a variant has multiple values in `SID`
Details on how to test can be found here: [ENSVAR-5284](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5284)
> Update import_vcf script for EVA

- scripts/import/import_EPMC.pl
[ENSVAR-5272](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5272)
> Fixing citation authors 

- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/Constants.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportG2P.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportGWAS.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportHuman.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/InitPhenotypeAnnotation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/OntologyMapping.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/PhenotypeAnnotation_conf.pm
[ENSVAR-5270](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5270)
[ENSVAR-4729](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4729)
> Update phenotype gwas g2p

- modules/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm
- modules/Bio/EnsEMBL/Variation/Utils/VEP.pm
[ENSVAR-4183](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4183)
> Making mane to be the likely picked

- scripts/import/import_EPMC.pl
When checking for the dbSNP citations:
- truncate title if length > max
- remove <> from title
- fix authors encoding
> Update citation import script 

- scripts/import/import_clinvar_xml
[ENSVAR-5271](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5271)
> Update ClinVar import script - fetch phenotypes

- scripts/misc/update_match_seq_region_ids.pl
A few bugs related to human seq_region data need to be updated. This PR test this script in human new datasets.
1) run `update_match_seq_region_ids.pl` in a new case.
> fix: bugs in update_match_seq_region_ids.pl

- modules/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm
- modules/Bio/EnsEMBL/Variation/Utils/VEP.pm
[ENSVAR-5409](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5409)
Needs to be reverted to 109
> updating this changes for pick option

- modules/Bio/EnsEMBL/Variation/Pipeline/FinishRegulationEffect.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/RegulationEffect_conf.pm
- Add consequence terms: 'start_retained_variant', 'splice_donor_5th_base_variant', 'splice_donor_region_variant', 'splice_polypyrimidine_tract_variant'
- Print logs to a file
> Update Regulatory pipeline

- .travis.yml
- README.md
Every release we need to update a few things to travis and README.
Reference last PR: https://github.com/Ensembl/ensembl-variation/pull/877
None.
> feat: add travis + README to release 110

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
[ENSVAR-5432](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5432): Configure VCF for Prairie vole
[ENSVAR-5465](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5465): Configure VCF for Gibbon
Check also https://github.com/Ensembl/public-plugins/pull/656
> Fetch EVA variants for Gibbon and Prairie vole

- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/FinishPhenotypeAnnotation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/OntologyMapping.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/PhenotypeAnnotation_conf.pm
[ENSVAR-3350](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-3350)
Tested using run_type - ZFIN and AnimalSet.
eHive url - http://guihive.ebi.ac.uk:8080/versions/96/?driver=mysql&username=ensadmin&host=mysql-ens-var-prod-4&port=4694&dbname=snhossain_ehive_phenotype_annotation_109&passwd=xxxxx
Test registry file - 
`/hps/nobackup/flicek/ensembl/variation/snhossain/release/110/test/phenotype_import/[ensembl.registry|ensembl.registry_animallab]`
> Add datachecks to phenotype pipeline

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
[ENSVAR-5449](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5449)
[ENSVAR-5460](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5460)
> Adding zebrafinch and updating crab macaque

- modules/Bio/EnsEMBL/Variation/Pipeline/CheckTranscriptVariation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/VariationConsequence_conf.pm
Details: [ENSVAR-3130](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-3130)
> Add datachecks to variation consequence pipeline

- modules/Bio/EnsEMBL/Variation/Pipeline/FinishRegulationEffect.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/RegulationEffect_conf.pm
* Deprecate `update_vf` so the only required parameter is `only_update_vf`
* Autoflush STDOUT to print to log file immediately
> Regulation pipeline: deprecate update_vf parameter + autoflush STDOUT

- modules/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm
- modules/t/variationFeatureAdaptor.t
[ENSVAR-2603](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-2603)
This PR allows to customise the region limit supported by HGVSg. If the HGVSg is equal to or bigger than this limit, it will throw an error.
Test this PR in https://github.com/Ensembl/ensembl-vep/pull/1406
> Add argument for HGVSg region limit

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
[ENSVAR-5339](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5339)
> Update paths to GERP conservation scores (110)

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
Sister PR of - https://github.com/Ensembl/public-plugins/pull/690
> Remove some vcf species from config 

- .travis.yml
- README.md
> Changes to the configuration files

- scripts/import/import_clinvar_xml
[ENSVAR-5483](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5483) - done 
[ENSVAR-4987](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4987) - done
[ENSVAR-501](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-501) - done
> Clinvar updates 

- modules/Bio/EnsEMBL/Variation/DBSQL/PhenotypeFeatureAdaptor.pm
[ENSVAR-5773](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5773)
From ClinVar get the risk_allele (alt allele) and the allele_symbol (ref allele). 
Linked to: https://github.com/Ensembl/ensembl-vep/pull/1423
> Update PhenotypeFeatureAdaptor - fetch allele symbol from phenotype_feature_attrib

- scripts/import/import_clinvar_xml
> Adding some changes to clinvar

- scripts/import/map_hgmd_coord.pl
Replace `$slice->get_seq_region_id;` this method does not work correctly.
As HGMD has the same chr names as Ensembl we can fetch the seq regions directly.
> Update HGMD script

- scripts/import/dbSNP_v2/update_new_sets.pl
[ENSVAR-5561](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5561)
> variation set update

- modules/Bio/EnsEMBL/Variation/Pipeline/EquivalentAlleles/EquivalentAlleles_conf.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/EquivalentAlleles/FindEquivalentAlleles.pm
[ENSVAR-5588](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5588)
- Auto-reconnect to MySQL database to avoid errors related with connection going away
- Optimise settings
> Equivalent Alleles: auto-reconnect to MySQL database

- modules/Bio/EnsEMBL/Variation/DBSQL/PhenotypeFeatureAdaptor.pm
Revert https://github.com/Ensembl/ensembl-variation/pull/995
> Update PhenotypeFeatureAdaptor  - remove allele_symbol

- modules/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm
Related to - https://github.com/Ensembl/VEP_plugins/pull/624
> Allow HGVSp to be single letter

- modules/Bio/EnsEMBL/Variation/Pipeline/UpdateVariationFeature.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/VariationConsequence_conf.pm
Re: ENSVAR-5938
Has been run successfully. Can compare the update vf code to code in 107 or earlier to confirm just reverting.
> Revert to old update vf mode for speed

- modules/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm
- modules/t/vep.t
Ticket: [ENSVAR-778](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-778)
Codon and cds for reference allele are incorrect resulting in incorrect peptide and HGVSp
```
3:g.41266031_41266626del
```
> Fix ref codon and ref peptide used for HGVSp

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
[ENSVAR-5653](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5653)
> GERP configuration for 111 

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
[ENSVAR-5657](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5657)
> Changes for the genotype and population files 

- modules/t/test-genome-DBs/homo_sapiens/funcgen/meta.txt
- modules/t/test-genome-DBs/homo_sapiens/funcgen/table.sql
- modules/t/test-genome-DBs/homo_sapiens/variation/meta.txt
- modules/t/test-genome-DBs/homo_sapiens/variation/table.sql
- sql/patch_112_113_a.sql
- sql/patch_112_113_b.sql
- sql/table.sql
[ENSVAR-6225](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6225)
> Schema update to 113 + patch meta_key

- modules/Bio/EnsEMBL/Variation/Utils/VariationEffect.pm
[ENSVAR-4348](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4348)
> [ENSVAR-4348]- stop_retained

- scripts/docs/data_files/vcf_species_list_112.json
> new species list

- scripts/import/import_cosmic.pl
- scripts/import/remove_cosmic_or_hgmd.pl
Details on how to test: [ENSVAR-6328](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6328)
> Update COSMIC - add option to populate transcript_variation

- scripts/docs/update_web_vep_plugins_documentation.pl
Related with https://github.com/Ensembl/public-plugins/pull/790
> Fix less and more than symbols in usage examples

- modules/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm
Ticket: [ENSVAR-6078](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6078)
> CDS code change testing 

- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportOMIA.pm
> Update phenotype pipeline - fix OMIA file download

- modules/Bio/EnsEMBL/Variation/Pipeline/ProteinFunction/ProteinFunction_conf.pm
Updating CADD and dbNSFP files to latest versions.
> Updating cadd and dbNSFP paths

- modules/Bio/EnsEMBL/Variation/Pipeline/DumpHGVS/DumpHGVS_conf.pm
ENSVAR-6302: Updates required to run pipeline in SLURM
> Update DumpHGVS pipeline for SLURM

- modules/Bio/EnsEMBL/Variation/Pipeline/ReleaseDataDumps/ReleaseDumps_conf.pm
[ENSVAR-6277](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6277)
> Add slurm configuration for ReleaseDump pipeline

- scripts/import/import_clinvar_xml
Check this ticket for more details: [ENSVAR-5483](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5483)
> Update ClinVar to map YPAR to chrX and chrY

- modules/Bio/EnsEMBL/Variation/Pipeline/RegulationEffect.pm
[ENSVAR-6367](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6367)
> Skip adding EMER regulatory feature in variation DB

- modules/Bio/EnsEMBL/Variation/Utils/VEP.pm
Test pipeline:
http://guihive.ebi.ac.uk:8080/versions/96/?driver=mysql&username=ensadmin&host=mysql-ens-var-prod-4&port=4694&dbname=snhossain_dump_vep_human_113_test&passwd=xxxxx
> Dump gencode_primary attribute in cache

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
[ENSVAR-6201](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6201)
Related PRs:
public-plugins: https://github.com/Ensembl/public-plugins/pull/820
ebi-plugins: https://github.com/Ensembl/ebi-plugins/pull/176
> Updated version in vcf_config

- modules/t/test-genome-DBs/homo_sapiens/core/meta.txt
- modules/t/test-genome-DBs/homo_sapiens/core/table.sql
- modules/t/test-genome-DBs/homo_sapiens/funcgen/meta.txt
- modules/t/test-genome-DBs/homo_sapiens/funcgen/table.sql
- modules/t/test-genome-DBs/homo_sapiens/otherfeatures/meta.txt
- modules/t/test-genome-DBs/homo_sapiens/otherfeatures/table.sql
- modules/t/test-genome-DBs/homo_sapiens/variation/meta.txt
- modules/t/test-genome-DBs/homo_sapiens/variation/table.sql
- modules/t/test-genome-DBs/multi/ontology/meta.txt
- modules/t/test-genome-DBs/multi/ontology/table.sql
- sql/attrib_entries.sql
for e114 - 
- test database patches 
- attrib_entries.sql update
* ensembl-fungen have not updated sql/ yet. It is done manually in this PR.
> Patching test database (e114)

- modules/Bio/EnsEMBL/Variation/Pipeline/RegulationEffect_conf.pm
Add long queue to finish_regulation_effect
> Update regulation pipeline

- modules/Bio/EnsEMBL/Variation/Utils/Config.pm
- modules/Bio/EnsEMBL/Variation/Utils/VEP.pm
Simpler version of https://github.com/Ensembl/ensembl-variation/pull/1075
Remove function swapping with ensembl-vep.
> Remove redundant SO term hash

- scripts/import/import_hgmd.pl
Ticket: [ENSVAR-6688](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6688)
> Update hgmd script - set somatic to 0 when creating variation_feature

- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportG2P.pm
https://embl.atlassian.net/browse/ENSVAR-6809 - A minor fix for the Phenotype pipeline.
>  G2P change from Hearing loss to ear

- modules/Bio/EnsEMBL/Variation/DBSQL/vcf_config.json
[ENSVAR-6813](https://embl.atlassian.net/browse/ENSVAR-6813)
related PR - https://github.com/Ensembl/public-plugins/pull/882
> EVA species update to release 7

- sql/patch_115_116_a.sql.sql
> schema patch

- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/Constants.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportGENCC.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/ImportHuman.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/InitPhenotypeAnnotation.pm
- modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation/PhenotypeAnnotation_conf.pm
This PR adds GenCC as a new data source to the [PhenotypeAnnotation pipeline](https://github.com/Ensembl/ensembl-variation/tree/release/114/modules/Bio/EnsEMBL/Variation/Pipeline/PhenotypeAnnotation). The GenCC data can be downloaded from [here](https://search.thegencc.org/download/action/submissions-export-csv). This addresses JIRA ticket ENSVAR 4970.
- `Constants.pm` — add `GENCC` and include it in `HUMAN_GENE`
- `InitPhenotypeAnnotation.pm` — point `GENCC` to human branch
- `PhenotypeAnnotation_conf.pm` — add `import_gencc` and `check_gencc`
I requested the `gencc` attributes through the masterattribtype service as below: 
I have tested that `ImportGENCC.pm` does indeed insert info into the relevant tables by doing the following: 
- I grabbed the first 50 rows (header + 49 entries) of …
> Add GenCC as a data source

- scripts/python/download_cgc_file.py
Ticket: [ENSVAR-6801](https://embl.atlassian.net/browse/ENSVAR-6801)
> Update script to download open targets file
